using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using WinformsKontrolleri.Model;

namespace WinformsKontrolleri
{
    public partial class ComboBoxDataBound : Form
    {
        List<Sehir> sehirler = new List<Sehir>();
        List<Ilce> ilceler = new List<Ilce>();
        public ComboBoxDataBound()
        {
            InitializeComponent();
            SehirDoldur();
            IlceDoldur();
            cb_sehirler.DisplayMember = "Isim";
            cb_sehirler.ValueMember = "ID";
            cb_sehirler.DataSource = sehirler;
            cb_sehirler.SelectedValue = 1;

            cb_ilceler.DisplayMember = "Isim";
            cb_ilceler.ValueMember = "ID";
        }



        public void SehirDoldur()
        {
            sehirler.Add(new Sehir() { ID = 1, Isim = "Adana" });
            sehirler.Add(new Sehir() { ID = 2, Isim = "Adıyaman" });
            sehirler.Add(new Sehir() { ID = 3, Isim = "Afyonkarahisar" });
            sehirler.Add(new Sehir() { ID = 4, Isim = "Ağrı" });
            sehirler.Add(new Sehir() { ID = 5, Isim = "Amasya" });
            sehirler.Add(new Sehir() { ID = 6, Isim = "Ankara" });
            sehirler.Add(new Sehir() { ID = 7, Isim = "Antalya" });
            sehirler.Add(new Sehir() { ID = 8, Isim = "Artvin" });
            sehirler.Add(new Sehir() { ID = 9, Isim = "Aydın" });
            sehirler.Add(new Sehir() { ID = 10, Isim = "Balıkesir" });
            sehirler.Add(new Sehir() { ID = 11, Isim = "Bilecik" });
            sehirler.Add(new Sehir() { ID = 12, Isim = "Bingöl" });
            sehirler.Add(new Sehir() { ID = 13, Isim = "Bitlis" });
            sehirler.Add(new Sehir() { ID = 14, Isim = "Bolu" });
            sehirler.Add(new Sehir() { ID = 15, Isim = "Burdur" });
            sehirler.Add(new Sehir() { ID = 16, Isim = "Bursa" });
            sehirler.Add(new Sehir() { ID = 17, Isim = "Çanakkale" });
            sehirler.Add(new Sehir() { ID = 18, Isim = "Çankırı" });
            sehirler.Add(new Sehir() { ID = 19, Isim = "Çorum" });
            sehirler.Add(new Sehir() { ID = 20, Isim = "Denizli" });
            sehirler.Add(new Sehir() { ID = 21, Isim = "Diyarbakır" });
            sehirler.Add(new Sehir() { ID = 22, Isim = "Edirne" });
            sehirler.Add(new Sehir() { ID = 23, Isim = "Elazığ" });
            sehirler.Add(new Sehir() { ID = 24, Isim = "Erzincan" });
            sehirler.Add(new Sehir() { ID = 25, Isim = "Erzurum" });
            sehirler.Add(new Sehir() { ID = 26, Isim = "Eskişehir" });
            sehirler.Add(new Sehir() { ID = 27, Isim = "Gaziantep" });
            sehirler.Add(new Sehir() { ID = 28, Isim = "Giresun" });
            sehirler.Add(new Sehir() { ID = 29, Isim = "Gümüşhane" });
            sehirler.Add(new Sehir() { ID = 30, Isim = "Hakkari" });
            sehirler.Add(new Sehir() { ID = 31, Isim = "Hatay" });
            sehirler.Add(new Sehir() { ID = 32, Isim = "Isparta" });
            sehirler.Add(new Sehir() { ID = 33, Isim = "Mersin" });
            sehirler.Add(new Sehir() { ID = 34, Isim = "İstanbul" });
            sehirler.Add(new Sehir() { ID = 35, Isim = "İzmir" });
            sehirler.Add(new Sehir() { ID = 36, Isim = "Kars" });
            sehirler.Add(new Sehir() { ID = 37, Isim = "Kastamonu" });
            sehirler.Add(new Sehir() { ID = 38, Isim = "Kayseri" });
            sehirler.Add(new Sehir() { ID = 39, Isim = "Kırklareli" });
            sehirler.Add(new Sehir() { ID = 40, Isim = "Kırşehir" });
            sehirler.Add(new Sehir() { ID = 41, Isim = "Kocaeli" });
            sehirler.Add(new Sehir() { ID = 42, Isim = "Konya" });
            sehirler.Add(new Sehir() { ID = 43, Isim = "Kütahya" });
            sehirler.Add(new Sehir() { ID = 44, Isim = "Malatya" });
            sehirler.Add(new Sehir() { ID = 45, Isim = "Manisa" });
            sehirler.Add(new Sehir() { ID = 46, Isim = "Kahramanmaraş" });
            sehirler.Add(new Sehir() { ID = 47, Isim = "Mardin" });
            sehirler.Add(new Sehir() { ID = 48, Isim = "Muğla" });
            sehirler.Add(new Sehir() { ID = 49, Isim = "Muş" });
            sehirler.Add(new Sehir() { ID = 50, Isim = "Nevşehir" });
            sehirler.Add(new Sehir() { ID = 51, Isim = "Niğde" });
            sehirler.Add(new Sehir() { ID = 52, Isim = "Ordu" });
            sehirler.Add(new Sehir() { ID = 53, Isim = "Rize" });
            sehirler.Add(new Sehir() { ID = 54, Isim = "Sakarya" });
            sehirler.Add(new Sehir() { ID = 55, Isim = "Samsun" });
            sehirler.Add(new Sehir() { ID = 56, Isim = "Siirt" });
            sehirler.Add(new Sehir() { ID = 57, Isim = "Sinop" });
            sehirler.Add(new Sehir() { ID = 58, Isim = "Sivas" });
            sehirler.Add(new Sehir() { ID = 59, Isim = "Tekirdağ" });
            sehirler.Add(new Sehir() { ID = 60, Isim = "Tokat" });
            sehirler.Add(new Sehir() { ID = 61, Isim = "Trabzon" });
            sehirler.Add(new Sehir() { ID = 62, Isim = "Tunceli" });
            sehirler.Add(new Sehir() { ID = 63, Isim = "Şanlıurfa" });
            sehirler.Add(new Sehir() { ID = 64, Isim = "Uşak" });
            sehirler.Add(new Sehir() { ID = 65, Isim = "Van" });
            sehirler.Add(new Sehir() { ID = 66, Isim = "Yozgat" });
            sehirler.Add(new Sehir() { ID = 67, Isim = "Zonguldak" });
            sehirler.Add(new Sehir() { ID = 68, Isim = "Aksaray" });
            sehirler.Add(new Sehir() { ID = 69, Isim = "Bayburt" });
            sehirler.Add(new Sehir() { ID = 70, Isim = "Karaman" });
            sehirler.Add(new Sehir() { ID = 71, Isim = "Kırıkkale" });
            sehirler.Add(new Sehir() { ID = 72, Isim = "Batman" });
            sehirler.Add(new Sehir() { ID = 73, Isim = "Şırnak" });
            sehirler.Add(new Sehir() { ID = 74, Isim = "Bartın" });
            sehirler.Add(new Sehir() { ID = 75, Isim = "Ardahan" });
            sehirler.Add(new Sehir() { ID = 76, Isim = "Iğdır" });
            sehirler.Add(new Sehir() { ID = 77, Isim = "Yalova" });
            sehirler.Add(new Sehir() { ID = 78, Isim = "Karabük" });
            sehirler.Add(new Sehir() { ID = 79, Isim = "Kilis" });
            sehirler.Add(new Sehir() { ID = 80, Isim = "Osmaniye" });
            sehirler.Add(new Sehir() { ID = 81, Isim = "Düzce" });
        }

        public void IlceDoldur()
        {
            ilceler.Add(new Ilce() { ID = 99133, Sehir_ID = 1, Isim = "Şakirpaşa Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2033, Sehir_ID = 1, Isim = "ÇUKUROVA" });
            ilceler.Add(new Ilce() { ID = 2032, Sehir_ID = 1, Isim = "SARIÇAM" });
            ilceler.Add(new Ilce() { ID = 1806, Sehir_ID = 1, Isim = "İMAMOĞLU" });
            ilceler.Add(new Ilce() { ID = 1757, Sehir_ID = 1, Isim = "ALADAĞ" });
            ilceler.Add(new Ilce() { ID = 1748, Sehir_ID = 1, Isim = "YÜREĞİR" });
            ilceler.Add(new Ilce() { ID = 1734, Sehir_ID = 1, Isim = "YUMURTALIK" });
            ilceler.Add(new Ilce() { ID = 1687, Sehir_ID = 1, Isim = "TUFANBEYLİ" });
            ilceler.Add(new Ilce() { ID = 1588, Sehir_ID = 1, Isim = "SAİMBEYLİ" });
            ilceler.Add(new Ilce() { ID = 1580, Sehir_ID = 1, Isim = "POZANTI" });
            ilceler.Add(new Ilce() { ID = 1486, Sehir_ID = 1, Isim = "KOZAN" });
            ilceler.Add(new Ilce() { ID = 1443, Sehir_ID = 1, Isim = "KARATAŞ" });
            ilceler.Add(new Ilce() { ID = 1437, Sehir_ID = 1, Isim = "KARAİSALI" });
            ilceler.Add(new Ilce() { ID = 1329, Sehir_ID = 1, Isim = "FEKE" });
            ilceler.Add(new Ilce() { ID = 1219, Sehir_ID = 1, Isim = "CEYHAN" });
            ilceler.Add(new Ilce() { ID = 1104, Sehir_ID = 1, Isim = "SEYHAN" });
            ilceler.Add(new Ilce() { ID = 99139, Sehir_ID = 2, Isim = "Adıyaman Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1989, Sehir_ID = 2, Isim = "TUT" });
            ilceler.Add(new Ilce() { ID = 1985, Sehir_ID = 2, Isim = "SİNCİK" });
            ilceler.Add(new Ilce() { ID = 1592, Sehir_ID = 2, Isim = "SAMSAT" });
            ilceler.Add(new Ilce() { ID = 1425, Sehir_ID = 2, Isim = "KAHTA" });
            ilceler.Add(new Ilce() { ID = 1354, Sehir_ID = 2, Isim = "GÖLBAŞI" });
            ilceler.Add(new Ilce() { ID = 1347, Sehir_ID = 2, Isim = "GERGER" });
            ilceler.Add(new Ilce() { ID = 1246, Sehir_ID = 2, Isim = "ÇELİKHAN" });
            ilceler.Add(new Ilce() { ID = 1182, Sehir_ID = 2, Isim = "BESNİ" });
            ilceler.Add(new Ilce() { ID = 1105, Sehir_ID = 2, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 99132, Sehir_ID = 3, Isim = "Afyon Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1961, Sehir_ID = 3, Isim = "KIZILÖREN" });
            ilceler.Add(new Ilce() { ID = 1944, Sehir_ID = 3, Isim = "HOCALAR" });
            ilceler.Add(new Ilce() { ID = 1923, Sehir_ID = 3, Isim = "EVCİLER" });
            ilceler.Add(new Ilce() { ID = 1906, Sehir_ID = 3, Isim = "ÇOBANLAR" });
            ilceler.Add(new Ilce() { ID = 1809, Sehir_ID = 3, Isim = "İSCEHİSAR" });
            ilceler.Add(new Ilce() { ID = 1773, Sehir_ID = 3, Isim = "BAYAT" });
            ilceler.Add(new Ilce() { ID = 1771, Sehir_ID = 3, Isim = "BAŞMAKÇI" });
            ilceler.Add(new Ilce() { ID = 1664, Sehir_ID = 3, Isim = "ŞUHUT" });
            ilceler.Add(new Ilce() { ID = 1639, Sehir_ID = 3, Isim = "SULTANDAĞI" });
            ilceler.Add(new Ilce() { ID = 1626, Sehir_ID = 3, Isim = "SİNANPAŞA" });
            ilceler.Add(new Ilce() { ID = 1594, Sehir_ID = 3, Isim = "SANDIKLI" });
            ilceler.Add(new Ilce() { ID = 1404, Sehir_ID = 3, Isim = "İHSANİYE" });
            ilceler.Add(new Ilce() { ID = 1306, Sehir_ID = 3, Isim = "EMİRDAĞ" });
            ilceler.Add(new Ilce() { ID = 1281, Sehir_ID = 3, Isim = "DİNAR" });
            ilceler.Add(new Ilce() { ID = 1267, Sehir_ID = 3, Isim = "DAZKIRI" });
            ilceler.Add(new Ilce() { ID = 1239, Sehir_ID = 3, Isim = "ÇAY" });
            ilceler.Add(new Ilce() { ID = 1200, Sehir_ID = 3, Isim = "BOLVADİN" });
            ilceler.Add(new Ilce() { ID = 1108, Sehir_ID = 3, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 99140, Sehir_ID = 4, Isim = "Ağrı Ahmed-i Hani Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1691, Sehir_ID = 4, Isim = "TUTAK" });
            ilceler.Add(new Ilce() { ID = 1667, Sehir_ID = 4, Isim = "TAŞLIÇAY" });
            ilceler.Add(new Ilce() { ID = 1568, Sehir_ID = 4, Isim = "PATNOS" });
            ilceler.Add(new Ilce() { ID = 1379, Sehir_ID = 4, Isim = "HAMUR" });
            ilceler.Add(new Ilce() { ID = 1301, Sehir_ID = 4, Isim = "ELEŞKİRT" });
            ilceler.Add(new Ilce() { ID = 1287, Sehir_ID = 4, Isim = "DOĞUBAYAZIT" });
            ilceler.Add(new Ilce() { ID = 1283, Sehir_ID = 4, Isim = "DİYADİN" });
            ilceler.Add(new Ilce() { ID = 1111, Sehir_ID = 4, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 99166, Sehir_ID = 5, Isim = "Amasya Merzifon Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1938, Sehir_ID = 5, Isim = "HAMAMÖZÜ" });
            ilceler.Add(new Ilce() { ID = 1668, Sehir_ID = 5, Isim = "TAŞOVA" });
            ilceler.Add(new Ilce() { ID = 1641, Sehir_ID = 5, Isim = "SULUOVA" });
            ilceler.Add(new Ilce() { ID = 1524, Sehir_ID = 5, Isim = "MERZİFON" });
            ilceler.Add(new Ilce() { ID = 1368, Sehir_ID = 5, Isim = "GÜMÜŞHACIKÖY" });
            ilceler.Add(new Ilce() { ID = 1363, Sehir_ID = 5, Isim = "GÖYNÜCEK" });
            ilceler.Add(new Ilce() { ID = 1134, Sehir_ID = 5, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 99134, Sehir_ID = 6, Isim = "Ankara Esenboğa Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2034, Sehir_ID = 6, Isim = "PURSAKLAR" });
            ilceler.Add(new Ilce() { ID = 1924, Sehir_ID = 6, Isim = "EVREN" });
            ilceler.Add(new Ilce() { ID = 1922, Sehir_ID = 6, Isim = "ETİMESGUT" });
            ilceler.Add(new Ilce() { ID = 1872, Sehir_ID = 6, Isim = "AKYURT" });
            ilceler.Add(new Ilce() { ID = 1815, Sehir_ID = 6, Isim = "KAHRAMANKAZAN" });
            ilceler.Add(new Ilce() { ID = 1747, Sehir_ID = 6, Isim = "SİNCAN" });
            ilceler.Add(new Ilce() { ID = 1746, Sehir_ID = 6, Isim = "MAMAK" });
            ilceler.Add(new Ilce() { ID = 1745, Sehir_ID = 6, Isim = "KEÇİÖREN" });
            ilceler.Add(new Ilce() { ID = 1744, Sehir_ID = 6, Isim = "GÖLBAŞI" });
            ilceler.Add(new Ilce() { ID = 1723, Sehir_ID = 6, Isim = "YENİMAHALLE" });
            ilceler.Add(new Ilce() { ID = 1658, Sehir_ID = 6, Isim = "ŞEREFLİKOÇHİSAR" });
            ilceler.Add(new Ilce() { ID = 1578, Sehir_ID = 6, Isim = "POLATLI" });
            ilceler.Add(new Ilce() { ID = 1539, Sehir_ID = 6, Isim = "NALLIHAN" });
            ilceler.Add(new Ilce() { ID = 1473, Sehir_ID = 6, Isim = "KIZILCAHAMAM" });
            ilceler.Add(new Ilce() { ID = 1427, Sehir_ID = 6, Isim = "KALECİK" });
            ilceler.Add(new Ilce() { ID = 1387, Sehir_ID = 6, Isim = "HAYMANA" });
            ilceler.Add(new Ilce() { ID = 1365, Sehir_ID = 6, Isim = "GÜDÜL" });
            ilceler.Add(new Ilce() { ID = 1302, Sehir_ID = 6, Isim = "ELMADAĞ" });
            ilceler.Add(new Ilce() { ID = 1260, Sehir_ID = 6, Isim = "ÇUBUK" });
            ilceler.Add(new Ilce() { ID = 1231, Sehir_ID = 6, Isim = "ÇANKAYA" });
            ilceler.Add(new Ilce() { ID = 1227, Sehir_ID = 6, Isim = "ÇAMLIDERE" });
            ilceler.Add(new Ilce() { ID = 1187, Sehir_ID = 6, Isim = "BEYPAZARI" });
            ilceler.Add(new Ilce() { ID = 1167, Sehir_ID = 6, Isim = "BALA" });
            ilceler.Add(new Ilce() { ID = 1157, Sehir_ID = 6, Isim = "AYAŞ" });
            ilceler.Add(new Ilce() { ID = 1130, Sehir_ID = 6, Isim = "ALTINDAĞ" });
            ilceler.Add(new Ilce() { ID = 99141, Sehir_ID = 7, Isim = "Gazipaşa Havalimanı" });
            ilceler.Add(new Ilce() { ID = 99135, Sehir_ID = 7, Isim = "Antalya Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2039, Sehir_ID = 7, Isim = "MURATPAŞA" });
            ilceler.Add(new Ilce() { ID = 2038, Sehir_ID = 7, Isim = "KONYAALTI" });
            ilceler.Add(new Ilce() { ID = 2037, Sehir_ID = 7, Isim = "KEPEZ" });
            ilceler.Add(new Ilce() { ID = 2036, Sehir_ID = 7, Isim = "DÖŞEMEALTI" });
            ilceler.Add(new Ilce() { ID = 2035, Sehir_ID = 7, Isim = "AKSU" });
            ilceler.Add(new Ilce() { ID = 1959, Sehir_ID = 7, Isim = "KEMER" });
            ilceler.Add(new Ilce() { ID = 1946, Sehir_ID = 7, Isim = "İBRADI" });
            ilceler.Add(new Ilce() { ID = 1811, Sehir_ID = 7, Isim = "DEMRE" });
            ilceler.Add(new Ilce() { ID = 1616, Sehir_ID = 7, Isim = "SERİK" });
            ilceler.Add(new Ilce() { ID = 1512, Sehir_ID = 7, Isim = "MANAVGAT" });
            ilceler.Add(new Ilce() { ID = 1492, Sehir_ID = 7, Isim = "KUMLUCA" });
            ilceler.Add(new Ilce() { ID = 1483, Sehir_ID = 7, Isim = "KORKUTELİ" });
            ilceler.Add(new Ilce() { ID = 1451, Sehir_ID = 7, Isim = "KAŞ" });
            ilceler.Add(new Ilce() { ID = 1370, Sehir_ID = 7, Isim = "GÜNDOĞMUŞ" });
            ilceler.Add(new Ilce() { ID = 1337, Sehir_ID = 7, Isim = "GAZİPAŞA" });
            ilceler.Add(new Ilce() { ID = 1333, Sehir_ID = 7, Isim = "FİNİKE" });
            ilceler.Add(new Ilce() { ID = 1303, Sehir_ID = 7, Isim = "ELMALI" });
            ilceler.Add(new Ilce() { ID = 1138, Sehir_ID = 7, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1126, Sehir_ID = 7, Isim = "ALANYA" });
            ilceler.Add(new Ilce() { ID = 1121, Sehir_ID = 7, Isim = "AKSEKİ" });
            ilceler.Add(new Ilce() { ID = 2105, Sehir_ID = 8, Isim = "KEMALPAŞA" });
            ilceler.Add(new Ilce() { ID = 1828, Sehir_ID = 8, Isim = "MURGUL" });
            ilceler.Add(new Ilce() { ID = 1736, Sehir_ID = 8, Isim = "YUSUFELİ" });
            ilceler.Add(new Ilce() { ID = 1653, Sehir_ID = 8, Isim = "ŞAVŞAT" });
            ilceler.Add(new Ilce() { ID = 1395, Sehir_ID = 8, Isim = "HOPA" });
            ilceler.Add(new Ilce() { ID = 1202, Sehir_ID = 8, Isim = "BORÇKA" });
            ilceler.Add(new Ilce() { ID = 1152, Sehir_ID = 8, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1147, Sehir_ID = 8, Isim = "ARHAVİ" });
            ilceler.Add(new Ilce() { ID = 1145, Sehir_ID = 8, Isim = "ARDANUÇ" });
            ilceler.Add(new Ilce() { ID = 2076, Sehir_ID = 9, Isim = "EFELER" });
            ilceler.Add(new Ilce() { ID = 2000, Sehir_ID = 9, Isim = "DİDİM" });
            ilceler.Add(new Ilce() { ID = 1968, Sehir_ID = 9, Isim = "KÖŞK" });
            ilceler.Add(new Ilce() { ID = 1957, Sehir_ID = 9, Isim = "KARPUZLU" });
            ilceler.Add(new Ilce() { ID = 1807, Sehir_ID = 9, Isim = "İNCİRLİOVA" });
            ilceler.Add(new Ilce() { ID = 1781, Sehir_ID = 9, Isim = "BUHARKENT" });
            ilceler.Add(new Ilce() { ID = 1724, Sehir_ID = 9, Isim = "YENİPAZAR" });
            ilceler.Add(new Ilce() { ID = 1640, Sehir_ID = 9, Isim = "SULTANHİSAR" });
            ilceler.Add(new Ilce() { ID = 1637, Sehir_ID = 9, Isim = "SÖKE" });
            ilceler.Add(new Ilce() { ID = 1542, Sehir_ID = 9, Isim = "NAZİLLİ" });
            ilceler.Add(new Ilce() { ID = 1498, Sehir_ID = 9, Isim = "KUYUCAK" });
            ilceler.Add(new Ilce() { ID = 1497, Sehir_ID = 9, Isim = "KUŞADASI" });
            ilceler.Add(new Ilce() { ID = 1479, Sehir_ID = 9, Isim = "KOÇARLI" });
            ilceler.Add(new Ilce() { ID = 1435, Sehir_ID = 9, Isim = "KARACASU" });
            ilceler.Add(new Ilce() { ID = 1348, Sehir_ID = 9, Isim = "GERMENCİK" });
            ilceler.Add(new Ilce() { ID = 1256, Sehir_ID = 9, Isim = "ÇİNE" });
            ilceler.Add(new Ilce() { ID = 1206, Sehir_ID = 9, Isim = "BOZDOĞAN" });
            ilceler.Add(new Ilce() { ID = 1159, Sehir_ID = 9, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 99142, Sehir_ID = 10, Isim = "Balıkesir Merkez Havalimanı" });
            ilceler.Add(new Ilce() { ID = 99107, Sehir_ID = 10, Isim = "Balıkesir Koca Seyit Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2078, Sehir_ID = 10, Isim = "KARESİ" });
            ilceler.Add(new Ilce() { ID = 2077, Sehir_ID = 10, Isim = "ALTIEYLÜL" });
            ilceler.Add(new Ilce() { ID = 1928, Sehir_ID = 10, Isim = "GÖMEÇ" });
            ilceler.Add(new Ilce() { ID = 1824, Sehir_ID = 10, Isim = "MARMARA" });
            ilceler.Add(new Ilce() { ID = 1644, Sehir_ID = 10, Isim = "SUSURLUK" });
            ilceler.Add(new Ilce() { ID = 1619, Sehir_ID = 10, Isim = "SINDIRGI" });
            ilceler.Add(new Ilce() { ID = 1608, Sehir_ID = 10, Isim = "SAVAŞTEPE" });
            ilceler.Add(new Ilce() { ID = 1514, Sehir_ID = 10, Isim = "MANYAS" });
            ilceler.Add(new Ilce() { ID = 1462, Sehir_ID = 10, Isim = "KEPSUT" });
            ilceler.Add(new Ilce() { ID = 1418, Sehir_ID = 10, Isim = "İVRİNDİ" });
            ilceler.Add(new Ilce() { ID = 1384, Sehir_ID = 10, Isim = "HAVRAN" });
            ilceler.Add(new Ilce() { ID = 1360, Sehir_ID = 10, Isim = "GÖNEN" });
            ilceler.Add(new Ilce() { ID = 1310, Sehir_ID = 10, Isim = "ERDEK" });
            ilceler.Add(new Ilce() { ID = 1294, Sehir_ID = 10, Isim = "EDREMİT" });
            ilceler.Add(new Ilce() { ID = 1291, Sehir_ID = 10, Isim = "DURSUNBEY" });
            ilceler.Add(new Ilce() { ID = 1216, Sehir_ID = 10, Isim = "BURHANİYE" });
            ilceler.Add(new Ilce() { ID = 1191, Sehir_ID = 10, Isim = "BİGADİÇ" });
            ilceler.Add(new Ilce() { ID = 1171, Sehir_ID = 10, Isim = "BANDIRMA" });
            ilceler.Add(new Ilce() { ID = 1169, Sehir_ID = 10, Isim = "BALYA" });
            ilceler.Add(new Ilce() { ID = 1168, Sehir_ID = 10, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1161, Sehir_ID = 10, Isim = "AYVALIK" });
            ilceler.Add(new Ilce() { ID = 1948, Sehir_ID = 11, Isim = "İNHİSAR" });
            ilceler.Add(new Ilce() { ID = 1857, Sehir_ID = 11, Isim = "YENİPAZAR" });
            ilceler.Add(new Ilce() { ID = 1636, Sehir_ID = 11, Isim = "SÖĞÜT" });
            ilceler.Add(new Ilce() { ID = 1571, Sehir_ID = 11, Isim = "PAZARYERİ" });
            ilceler.Add(new Ilce() { ID = 1559, Sehir_ID = 11, Isim = "OSMANELİ" });
            ilceler.Add(new Ilce() { ID = 1359, Sehir_ID = 11, Isim = "GÖLPAZARI" });
            ilceler.Add(new Ilce() { ID = 1210, Sehir_ID = 11, Isim = "BOZÜYÜK" });
            ilceler.Add(new Ilce() { ID = 1192, Sehir_ID = 11, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 99167, Sehir_ID = 12, Isim = "Bingöl Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1996, Sehir_ID = 12, Isim = "YEDİSU" });
            ilceler.Add(new Ilce() { ID = 1855, Sehir_ID = 12, Isim = "YAYLADERE" });
            ilceler.Add(new Ilce() { ID = 1750, Sehir_ID = 12, Isim = "ADAKLI" });
            ilceler.Add(new Ilce() { ID = 1633, Sehir_ID = 12, Isim = "SOLHAN" });
            ilceler.Add(new Ilce() { ID = 1475, Sehir_ID = 12, Isim = "KİĞI" });
            ilceler.Add(new Ilce() { ID = 1446, Sehir_ID = 12, Isim = "KARLIOVA" });
            ilceler.Add(new Ilce() { ID = 1344, Sehir_ID = 12, Isim = "GENÇ" });
            ilceler.Add(new Ilce() { ID = 1193, Sehir_ID = 12, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1798, Sehir_ID = 13, Isim = "GÜROYMAK" });
            ilceler.Add(new Ilce() { ID = 1669, Sehir_ID = 13, Isim = "TATVAN" });
            ilceler.Add(new Ilce() { ID = 1537, Sehir_ID = 13, Isim = "MUTKİ" });
            ilceler.Add(new Ilce() { ID = 1394, Sehir_ID = 13, Isim = "HİZAN" });
            ilceler.Add(new Ilce() { ID = 1196, Sehir_ID = 13, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1112, Sehir_ID = 13, Isim = "AHLAT" });
            ilceler.Add(new Ilce() { ID = 1106, Sehir_ID = 13, Isim = "ADİLCEVAZ" });
            ilceler.Add(new Ilce() { ID = 1997, Sehir_ID = 14, Isim = "YENİÇAĞA" });
            ilceler.Add(new Ilce() { ID = 1916, Sehir_ID = 14, Isim = "DÖRTDİVAN" });
            ilceler.Add(new Ilce() { ID = 1610, Sehir_ID = 14, Isim = "SEBEN" });
            ilceler.Add(new Ilce() { ID = 1531, Sehir_ID = 14, Isim = "MUDURNU" });
            ilceler.Add(new Ilce() { ID = 1522, Sehir_ID = 14, Isim = "MENGEN" });
            ilceler.Add(new Ilce() { ID = 1466, Sehir_ID = 14, Isim = "KIBRISCIK" });
            ilceler.Add(new Ilce() { ID = 1364, Sehir_ID = 14, Isim = "GÖYNÜK" });
            ilceler.Add(new Ilce() { ID = 1346, Sehir_ID = 14, Isim = "GEREDE" });
            ilceler.Add(new Ilce() { ID = 1199, Sehir_ID = 14, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1903, Sehir_ID = 15, Isim = "ÇELTİKÇİ" });
            ilceler.Add(new Ilce() { ID = 1899, Sehir_ID = 15, Isim = "ÇAVDIR" });
            ilceler.Add(new Ilce() { ID = 1874, Sehir_ID = 15, Isim = "ALTINYAYLA" });
            ilceler.Add(new Ilce() { ID = 1816, Sehir_ID = 15, Isim = "KEMER" });
            ilceler.Add(new Ilce() { ID = 1813, Sehir_ID = 15, Isim = "KARAMANLI" });
            ilceler.Add(new Ilce() { ID = 1728, Sehir_ID = 15, Isim = "YEŞİLOVA" });
            ilceler.Add(new Ilce() { ID = 1672, Sehir_ID = 15, Isim = "TEFENNİ" });
            ilceler.Add(new Ilce() { ID = 1357, Sehir_ID = 15, Isim = "GÖLHİSAR" });
            ilceler.Add(new Ilce() { ID = 1215, Sehir_ID = 15, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1211, Sehir_ID = 15, Isim = "BUCAK" });
            ilceler.Add(new Ilce() { ID = 1109, Sehir_ID = 15, Isim = "AĞLASUN" });
            ilceler.Add(new Ilce() { ID = 99124, Sehir_ID = 16, Isim = "Bursa Yenişehir Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1960, Sehir_ID = 16, Isim = "KESTEL" });
            ilceler.Add(new Ilce() { ID = 1935, Sehir_ID = 16, Isim = "GÜRSU" });
            ilceler.Add(new Ilce() { ID = 1859, Sehir_ID = 16, Isim = "YILDIRIM" });
            ilceler.Add(new Ilce() { ID = 1832, Sehir_ID = 16, Isim = "OSMANGAZİ" });
            ilceler.Add(new Ilce() { ID = 1829, Sehir_ID = 16, Isim = "NİLÜFER" });
            ilceler.Add(new Ilce() { ID = 1799, Sehir_ID = 16, Isim = "HARMANCIK" });
            ilceler.Add(new Ilce() { ID = 1783, Sehir_ID = 16, Isim = "BÜYÜKORHAN" });
            ilceler.Add(new Ilce() { ID = 1725, Sehir_ID = 16, Isim = "YENİŞEHİR" });
            ilceler.Add(new Ilce() { ID = 1554, Sehir_ID = 16, Isim = "ORHANGAZİ" });
            ilceler.Add(new Ilce() { ID = 1553, Sehir_ID = 16, Isim = "ORHANELİ" });
            ilceler.Add(new Ilce() { ID = 1535, Sehir_ID = 16, Isim = "MUSTAFAKEMALPAŞA" });
            ilceler.Add(new Ilce() { ID = 1530, Sehir_ID = 16, Isim = "MUDANYA" });
            ilceler.Add(new Ilce() { ID = 1457, Sehir_ID = 16, Isim = "KELES" });
            ilceler.Add(new Ilce() { ID = 1434, Sehir_ID = 16, Isim = "KARACABEY" });
            ilceler.Add(new Ilce() { ID = 1420, Sehir_ID = 16, Isim = "İZNİK" });
            ilceler.Add(new Ilce() { ID = 1411, Sehir_ID = 16, Isim = "İNEGÖL" });
            ilceler.Add(new Ilce() { ID = 1343, Sehir_ID = 16, Isim = "GEMLİK" });
            ilceler.Add(new Ilce() { ID = 99168, Sehir_ID = 17, Isim = "Çanakkale Havalimanı" });
            ilceler.Add(new Ilce() { ID = 99128, Sehir_ID = 17, Isim = "Gökçeada Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1722, Sehir_ID = 17, Isim = "YENİCE" });
            ilceler.Add(new Ilce() { ID = 1503, Sehir_ID = 17, Isim = "LAPSEKİ" });
            ilceler.Add(new Ilce() { ID = 1408, Sehir_ID = 17, Isim = "GÖKÇEADA" });
            ilceler.Add(new Ilce() { ID = 1340, Sehir_ID = 17, Isim = "GELİBOLU" });
            ilceler.Add(new Ilce() { ID = 1326, Sehir_ID = 17, Isim = "EZİNE" });
            ilceler.Add(new Ilce() { ID = 1293, Sehir_ID = 17, Isim = "ECEABAT" });
            ilceler.Add(new Ilce() { ID = 1230, Sehir_ID = 17, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1229, Sehir_ID = 17, Isim = "ÇAN" });
            ilceler.Add(new Ilce() { ID = 1205, Sehir_ID = 17, Isim = "BOZCAADA" });
            ilceler.Add(new Ilce() { ID = 1190, Sehir_ID = 17, Isim = "BİGA" });
            ilceler.Add(new Ilce() { ID = 1180, Sehir_ID = 17, Isim = "BAYRAMİÇ" });
            ilceler.Add(new Ilce() { ID = 1160, Sehir_ID = 17, Isim = "AYVACIK" });
            ilceler.Add(new Ilce() { ID = 1963, Sehir_ID = 18, Isim = "KORGUN" });
            ilceler.Add(new Ilce() { ID = 1885, Sehir_ID = 18, Isim = "BAYRAMÖREN" });
            ilceler.Add(new Ilce() { ID = 1817, Sehir_ID = 18, Isim = "KIZILIRMAK" });
            ilceler.Add(new Ilce() { ID = 1765, Sehir_ID = 18, Isim = "ATKARACALAR" });
            ilceler.Add(new Ilce() { ID = 1718, Sehir_ID = 18, Isim = "YAPRAKLI" });
            ilceler.Add(new Ilce() { ID = 1649, Sehir_ID = 18, Isim = "ŞABANÖZÜ" });
            ilceler.Add(new Ilce() { ID = 1555, Sehir_ID = 18, Isim = "ORTA" });
            ilceler.Add(new Ilce() { ID = 1494, Sehir_ID = 18, Isim = "KURŞUNLU" });
            ilceler.Add(new Ilce() { ID = 1399, Sehir_ID = 18, Isim = "ILGAZ" });
            ilceler.Add(new Ilce() { ID = 1300, Sehir_ID = 18, Isim = "ELDİVAN" });
            ilceler.Add(new Ilce() { ID = 1248, Sehir_ID = 18, Isim = "ÇERKEŞ" });
            ilceler.Add(new Ilce() { ID = 1232, Sehir_ID = 18, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1976, Sehir_ID = 19, Isim = "OĞUZLAR" });
            ilceler.Add(new Ilce() { ID = 1972, Sehir_ID = 19, Isim = "LAÇİN" });
            ilceler.Add(new Ilce() { ID = 1911, Sehir_ID = 19, Isim = "DODURGA" });
            ilceler.Add(new Ilce() { ID = 1850, Sehir_ID = 19, Isim = "UĞURLUDAĞ" });
            ilceler.Add(new Ilce() { ID = 1778, Sehir_ID = 19, Isim = "BOĞAZKALE" });
            ilceler.Add(new Ilce() { ID = 1642, Sehir_ID = 19, Isim = "SUNGURLU" });
            ilceler.Add(new Ilce() { ID = 1558, Sehir_ID = 19, Isim = "OSMANCIK" });
            ilceler.Add(new Ilce() { ID = 1556, Sehir_ID = 19, Isim = "ORTAKÖY" });
            ilceler.Add(new Ilce() { ID = 1520, Sehir_ID = 19, Isim = "MECİTÖZÜ" });
            ilceler.Add(new Ilce() { ID = 1445, Sehir_ID = 19, Isim = "KARGI" });
            ilceler.Add(new Ilce() { ID = 1414, Sehir_ID = 19, Isim = "İSKİLİP" });
            ilceler.Add(new Ilce() { ID = 1259, Sehir_ID = 19, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1177, Sehir_ID = 19, Isim = "BAYAT" });
            ilceler.Add(new Ilce() { ID = 1124, Sehir_ID = 19, Isim = "ALACA" });
            ilceler.Add(new Ilce() { ID = 99143, Sehir_ID = 20, Isim = "Denizli Çardak Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2079, Sehir_ID = 20, Isim = "MERKEZEFENDİ" });
            ilceler.Add(new Ilce() { ID = 1889, Sehir_ID = 20, Isim = "BOZKURT" });
            ilceler.Add(new Ilce() { ID = 1888, Sehir_ID = 20, Isim = "BEYAĞAÇ" });
            ilceler.Add(new Ilce() { ID = 1881, Sehir_ID = 20, Isim = "BAKLAN" });
            ilceler.Add(new Ilce() { ID = 1871, Sehir_ID = 20, Isim = "PAMUKKALE" });
            ilceler.Add(new Ilce() { ID = 1840, Sehir_ID = 20, Isim = "SERİNHİSAR" });
            ilceler.Add(new Ilce() { ID = 1803, Sehir_ID = 20, Isim = "HONAZ" });
            ilceler.Add(new Ilce() { ID = 1774, Sehir_ID = 20, Isim = "BEKİLLİ" });
            ilceler.Add(new Ilce() { ID = 1769, Sehir_ID = 20, Isim = "BABADAĞ" });
            ilceler.Add(new Ilce() { ID = 1670, Sehir_ID = 20, Isim = "TAVAS" });
            ilceler.Add(new Ilce() { ID = 1597, Sehir_ID = 20, Isim = "SARAYKÖY" });
            ilceler.Add(new Ilce() { ID = 1426, Sehir_ID = 20, Isim = "KALE" });
            ilceler.Add(new Ilce() { ID = 1371, Sehir_ID = 20, Isim = "GÜNEY" });
            ilceler.Add(new Ilce() { ID = 1271, Sehir_ID = 20, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1257, Sehir_ID = 20, Isim = "ÇİVRİL" });
            ilceler.Add(new Ilce() { ID = 1233, Sehir_ID = 20, Isim = "ÇARDAK" });
            ilceler.Add(new Ilce() { ID = 1226, Sehir_ID = 20, Isim = "ÇAMELİ" });
            ilceler.Add(new Ilce() { ID = 1224, Sehir_ID = 20, Isim = "ÇAL" });
            ilceler.Add(new Ilce() { ID = 1214, Sehir_ID = 20, Isim = "BULDAN" });
            ilceler.Add(new Ilce() { ID = 1102, Sehir_ID = 20, Isim = "ACIPAYAM" });
            ilceler.Add(new Ilce() { ID = 99126, Sehir_ID = 21, Isim = "Diyarbakır Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2043, Sehir_ID = 21, Isim = "YENİŞEHİR" });
            ilceler.Add(new Ilce() { ID = 2042, Sehir_ID = 21, Isim = "SUR" });
            ilceler.Add(new Ilce() { ID = 2041, Sehir_ID = 21, Isim = "KAYAPINAR" });
            ilceler.Add(new Ilce() { ID = 2040, Sehir_ID = 21, Isim = "BAĞLAR" });
            ilceler.Add(new Ilce() { ID = 1962, Sehir_ID = 21, Isim = "KOCAKÖY" });
            ilceler.Add(new Ilce() { ID = 1791, Sehir_ID = 21, Isim = "EĞİL" });
            ilceler.Add(new Ilce() { ID = 1624, Sehir_ID = 21, Isim = "SİLVAN" });
            ilceler.Add(new Ilce() { ID = 1504, Sehir_ID = 21, Isim = "LİCE" });
            ilceler.Add(new Ilce() { ID = 1490, Sehir_ID = 21, Isim = "KULP" });
            ilceler.Add(new Ilce() { ID = 1389, Sehir_ID = 21, Isim = "HAZRO" });
            ilceler.Add(new Ilce() { ID = 1381, Sehir_ID = 21, Isim = "HANİ" });
            ilceler.Add(new Ilce() { ID = 1315, Sehir_ID = 21, Isim = "ERGANİ" });
            ilceler.Add(new Ilce() { ID = 1284, Sehir_ID = 21, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1278, Sehir_ID = 21, Isim = "DİCLE" });
            ilceler.Add(new Ilce() { ID = 1263, Sehir_ID = 21, Isim = "ÇÜNGÜŞ" });
            ilceler.Add(new Ilce() { ID = 1253, Sehir_ID = 21, Isim = "ÇINAR" });
            ilceler.Add(new Ilce() { ID = 1249, Sehir_ID = 21, Isim = "ÇERMİK" });
            ilceler.Add(new Ilce() { ID = 1195, Sehir_ID = 21, Isim = "BİSMİL" });
            ilceler.Add(new Ilce() { ID = 1988, Sehir_ID = 22, Isim = "SÜLOĞLU" });
            ilceler.Add(new Ilce() { ID = 1705, Sehir_ID = 22, Isim = "UZUNKÖPRÜ" });
            ilceler.Add(new Ilce() { ID = 1523, Sehir_ID = 22, Isim = "MERİÇ" });
            ilceler.Add(new Ilce() { ID = 1502, Sehir_ID = 22, Isim = "LALAPAŞA" });
            ilceler.Add(new Ilce() { ID = 1464, Sehir_ID = 22, Isim = "KEŞAN" });
            ilceler.Add(new Ilce() { ID = 1412, Sehir_ID = 22, Isim = "İPSALA" });
            ilceler.Add(new Ilce() { ID = 1385, Sehir_ID = 22, Isim = "HAVSA" });
            ilceler.Add(new Ilce() { ID = 1307, Sehir_ID = 22, Isim = "ENEZ" });
            ilceler.Add(new Ilce() { ID = 1295, Sehir_ID = 22, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 99144, Sehir_ID = 23, Isim = "Elazığ Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1873, Sehir_ID = 23, Isim = "ALACAKAYA" });
            ilceler.Add(new Ilce() { ID = 1820, Sehir_ID = 23, Isim = "KOVANCILAR" });
            ilceler.Add(new Ilce() { ID = 1762, Sehir_ID = 23, Isim = "ARICAK" });
            ilceler.Add(new Ilce() { ID = 1631, Sehir_ID = 23, Isim = "SİVRİCE" });
            ilceler.Add(new Ilce() { ID = 1566, Sehir_ID = 23, Isim = "PALU" });
            ilceler.Add(new Ilce() { ID = 1506, Sehir_ID = 23, Isim = "MADEN" });
            ilceler.Add(new Ilce() { ID = 1455, Sehir_ID = 23, Isim = "KEBAN" });
            ilceler.Add(new Ilce() { ID = 1438, Sehir_ID = 23, Isim = "KARAKOÇAN" });
            ilceler.Add(new Ilce() { ID = 1298, Sehir_ID = 23, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1173, Sehir_ID = 23, Isim = "BASKİL" });
            ilceler.Add(new Ilce() { ID = 1110, Sehir_ID = 23, Isim = "AĞIN" });
            ilceler.Add(new Ilce() { ID = 99109, Sehir_ID = 24, Isim = "Erzincan Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1977, Sehir_ID = 24, Isim = "OTLUKBELİ" });
            ilceler.Add(new Ilce() { ID = 1853, Sehir_ID = 24, Isim = "ÜZÜMLÜ" });
            ilceler.Add(new Ilce() { ID = 1675, Sehir_ID = 24, Isim = "TERCAN" });
            ilceler.Add(new Ilce() { ID = 1583, Sehir_ID = 24, Isim = "REFAHİYE" });
            ilceler.Add(new Ilce() { ID = 1460, Sehir_ID = 24, Isim = "KEMALİYE" });
            ilceler.Add(new Ilce() { ID = 1459, Sehir_ID = 24, Isim = "KEMAH" });
            ilceler.Add(new Ilce() { ID = 1406, Sehir_ID = 24, Isim = "İLİÇ" });
            ilceler.Add(new Ilce() { ID = 1318, Sehir_ID = 24, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1243, Sehir_ID = 24, Isim = "ÇAYIRLI" });
            ilceler.Add(new Ilce() { ID = 99100, Sehir_ID = 25, Isim = "Erzurum Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2045, Sehir_ID = 25, Isim = "YAKUTİYE" });
            ilceler.Add(new Ilce() { ID = 2044, Sehir_ID = 25, Isim = "PALANDÖKEN" });
            ilceler.Add(new Ilce() { ID = 1967, Sehir_ID = 25, Isim = "KÖPRÜKÖY" });
            ilceler.Add(new Ilce() { ID = 1945, Sehir_ID = 25, Isim = "AZİZİYE" });
            ilceler.Add(new Ilce() { ID = 1865, Sehir_ID = 25, Isim = "PAZARYOLU" });
            ilceler.Add(new Ilce() { ID = 1851, Sehir_ID = 25, Isim = "UZUNDERE" });
            ilceler.Add(new Ilce() { ID = 1812, Sehir_ID = 25, Isim = "KARAÇOBAN" });
            ilceler.Add(new Ilce() { ID = 1683, Sehir_ID = 25, Isim = "TORTUM" });
            ilceler.Add(new Ilce() { ID = 1674, Sehir_ID = 25, Isim = "TEKMAN" });
            ilceler.Add(new Ilce() { ID = 1657, Sehir_ID = 25, Isim = "ŞENKAYA" });
            ilceler.Add(new Ilce() { ID = 1567, Sehir_ID = 25, Isim = "PASİNLER" });
            ilceler.Add(new Ilce() { ID = 1551, Sehir_ID = 25, Isim = "OLUR" });
            ilceler.Add(new Ilce() { ID = 1550, Sehir_ID = 25, Isim = "OLTU" });
            ilceler.Add(new Ilce() { ID = 1540, Sehir_ID = 25, Isim = "NARMAN" });
            ilceler.Add(new Ilce() { ID = 1444, Sehir_ID = 25, Isim = "KARAYAZI" });
            ilceler.Add(new Ilce() { ID = 1416, Sehir_ID = 25, Isim = "İSPİR" });
            ilceler.Add(new Ilce() { ID = 1396, Sehir_ID = 25, Isim = "HORASAN" });
            ilceler.Add(new Ilce() { ID = 1392, Sehir_ID = 25, Isim = "HINIS" });
            ilceler.Add(new Ilce() { ID = 1319, Sehir_ID = 25, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1235, Sehir_ID = 25, Isim = "ÇAT" });
            ilceler.Add(new Ilce() { ID = 1153, Sehir_ID = 25, Isim = "AŞKALE" });
            ilceler.Add(new Ilce() { ID = 99162, Sehir_ID = 26, Isim = "Eskişehir Anadolu Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2047, Sehir_ID = 26, Isim = "TEPEBAŞI" });
            ilceler.Add(new Ilce() { ID = 2046, Sehir_ID = 26, Isim = "ODUNPAZARI" });
            ilceler.Add(new Ilce() { ID = 1973, Sehir_ID = 26, Isim = "MİHALGAZİ" });
            ilceler.Add(new Ilce() { ID = 1939, Sehir_ID = 26, Isim = "HAN" });
            ilceler.Add(new Ilce() { ID = 1934, Sehir_ID = 26, Isim = "GÜNYÜZÜ" });
            ilceler.Add(new Ilce() { ID = 1808, Sehir_ID = 26, Isim = "İNÖNÜ" });
            ilceler.Add(new Ilce() { ID = 1777, Sehir_ID = 26, Isim = "BEYLİKOVA" });
            ilceler.Add(new Ilce() { ID = 1759, Sehir_ID = 26, Isim = "ALPU" });
            ilceler.Add(new Ilce() { ID = 1632, Sehir_ID = 26, Isim = "SİVRİHİSAR" });
            ilceler.Add(new Ilce() { ID = 1618, Sehir_ID = 26, Isim = "SEYİTGAZİ" });
            ilceler.Add(new Ilce() { ID = 1599, Sehir_ID = 26, Isim = "SARICAKAYA" });
            ilceler.Add(new Ilce() { ID = 1527, Sehir_ID = 26, Isim = "MİHALIÇÇIK" });
            ilceler.Add(new Ilce() { ID = 1508, Sehir_ID = 26, Isim = "MAHMUDİYE" });
            ilceler.Add(new Ilce() { ID = 1322, Sehir_ID = 26, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1255, Sehir_ID = 26, Isim = "ÇİFTELER" });
            ilceler.Add(new Ilce() { ID = 99101, Sehir_ID = 27, Isim = "Gaziantep Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2700, Sehir_ID = 27, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1974, Sehir_ID = 27, Isim = "NURDAĞI" });
            ilceler.Add(new Ilce() { ID = 1956, Sehir_ID = 27, Isim = "KARKAMIŞ" });
            ilceler.Add(new Ilce() { ID = 1844, Sehir_ID = 27, Isim = "ŞEHİTKAMİL" });
            ilceler.Add(new Ilce() { ID = 1841, Sehir_ID = 27, Isim = "ŞAHİNBEY" });
            ilceler.Add(new Ilce() { ID = 1720, Sehir_ID = 27, Isim = "YAVUZELİ" });
            ilceler.Add(new Ilce() { ID = 1549, Sehir_ID = 27, Isim = "OĞUZELİ" });
            ilceler.Add(new Ilce() { ID = 1546, Sehir_ID = 27, Isim = "NİZİP" });
            ilceler.Add(new Ilce() { ID = 1415, Sehir_ID = 27, Isim = "İSLAHİYE" });
            ilceler.Add(new Ilce() { ID = 1139, Sehir_ID = 27, Isim = "ARABAN" });
            ilceler.Add(new Ilce() { ID = 1930, Sehir_ID = 28, Isim = "GÜCE" });
            ilceler.Add(new Ilce() { ID = 1912, Sehir_ID = 28, Isim = "DOĞANKENT" });
            ilceler.Add(new Ilce() { ID = 1894, Sehir_ID = 28, Isim = "ÇANAKÇI" });
            ilceler.Add(new Ilce() { ID = 1893, Sehir_ID = 28, Isim = "ÇAMOLUK" });
            ilceler.Add(new Ilce() { ID = 1854, Sehir_ID = 28, Isim = "YAĞLIDERE" });
            ilceler.Add(new Ilce() { ID = 1837, Sehir_ID = 28, Isim = "PİRAZİZ" });
            ilceler.Add(new Ilce() { ID = 1678, Sehir_ID = 28, Isim = "TİREBOLU" });
            ilceler.Add(new Ilce() { ID = 1654, Sehir_ID = 28, Isim = "ŞEBİNKARAHİSAR" });
            ilceler.Add(new Ilce() { ID = 1465, Sehir_ID = 28, Isim = "KEŞAP" });
            ilceler.Add(new Ilce() { ID = 1361, Sehir_ID = 28, Isim = "GÖRELE" });
            ilceler.Add(new Ilce() { ID = 1352, Sehir_ID = 28, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1324, Sehir_ID = 28, Isim = "EYNESİL" });
            ilceler.Add(new Ilce() { ID = 1320, Sehir_ID = 28, Isim = "ESPİYE" });
            ilceler.Add(new Ilce() { ID = 1272, Sehir_ID = 28, Isim = "DERELİ" });
            ilceler.Add(new Ilce() { ID = 1212, Sehir_ID = 28, Isim = "BULANCAK" });
            ilceler.Add(new Ilce() { ID = 1133, Sehir_ID = 28, Isim = "ALUCRA" });
            ilceler.Add(new Ilce() { ID = 1971, Sehir_ID = 29, Isim = "KÜRTÜN" });
            ilceler.Add(new Ilce() { ID = 1822, Sehir_ID = 29, Isim = "KÖSE" });
            ilceler.Add(new Ilce() { ID = 1684, Sehir_ID = 29, Isim = "TORUL" });
            ilceler.Add(new Ilce() { ID = 1660, Sehir_ID = 29, Isim = "ŞİRAN" });
            ilceler.Add(new Ilce() { ID = 1458, Sehir_ID = 29, Isim = "KELKİT" });
            ilceler.Add(new Ilce() { ID = 1369, Sehir_ID = 29, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 99110, Sehir_ID = 30, Isim = "Hakkâri Yüksekova Selahaddin Eyyubi Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1737, Sehir_ID = 30, Isim = "YÜKSEKOVA" });
            ilceler.Add(new Ilce() { ID = 1656, Sehir_ID = 30, Isim = "ŞEMDİNLİ" });
            ilceler.Add(new Ilce() { ID = 1377, Sehir_ID = 30, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1261, Sehir_ID = 30, Isim = "ÇUKURCA" });
            ilceler.Add(new Ilce() { ID = 99161, Sehir_ID = 31, Isim = "Hatay Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2083, Sehir_ID = 31, Isim = "PAYAS" });
            ilceler.Add(new Ilce() { ID = 2082, Sehir_ID = 31, Isim = "DEFNE" });
            ilceler.Add(new Ilce() { ID = 2081, Sehir_ID = 31, Isim = "ARSUZ" });
            ilceler.Add(new Ilce() { ID = 2080, Sehir_ID = 31, Isim = "ANTAKYA" });
            ilceler.Add(new Ilce() { ID = 1970, Sehir_ID = 31, Isim = "KUMLU" });
            ilceler.Add(new Ilce() { ID = 1887, Sehir_ID = 31, Isim = "BELEN" });
            ilceler.Add(new Ilce() { ID = 1792, Sehir_ID = 31, Isim = "ERZİN" });
            ilceler.Add(new Ilce() { ID = 1721, Sehir_ID = 31, Isim = "YAYLADAĞI" });
            ilceler.Add(new Ilce() { ID = 1591, Sehir_ID = 31, Isim = "SAMANDAĞ" });
            ilceler.Add(new Ilce() { ID = 1585, Sehir_ID = 31, Isim = "REYHANLI" });
            ilceler.Add(new Ilce() { ID = 1468, Sehir_ID = 31, Isim = "KIRIKHAN" });
            ilceler.Add(new Ilce() { ID = 1413, Sehir_ID = 31, Isim = "İSKENDERUN" });
            ilceler.Add(new Ilce() { ID = 1383, Sehir_ID = 31, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1382, Sehir_ID = 31, Isim = "HASSA" });
            ilceler.Add(new Ilce() { ID = 1289, Sehir_ID = 31, Isim = "DÖRTYOL" });
            ilceler.Add(new Ilce() { ID = 1131, Sehir_ID = 31, Isim = "ALTINÖZÜ" });
            ilceler.Add(new Ilce() { ID = 99112, Sehir_ID = 32, Isim = "Isparta Süleyman Demirel Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2001, Sehir_ID = 32, Isim = "YENİŞARBADEMLİ" });
            ilceler.Add(new Ilce() { ID = 1929, Sehir_ID = 32, Isim = "GÖNEN" });
            ilceler.Add(new Ilce() { ID = 1755, Sehir_ID = 32, Isim = "AKSU" });
            ilceler.Add(new Ilce() { ID = 1717, Sehir_ID = 32, Isim = "YALVAÇ" });
            ilceler.Add(new Ilce() { ID = 1699, Sehir_ID = 32, Isim = "ULUBORLU" });
            ilceler.Add(new Ilce() { ID = 1651, Sehir_ID = 32, Isim = "ŞARKİKARAAĞAÇ" });
            ilceler.Add(new Ilce() { ID = 1648, Sehir_ID = 32, Isim = "SÜTÇÜLER" });
            ilceler.Add(new Ilce() { ID = 1615, Sehir_ID = 32, Isim = "SENİRKENT" });
            ilceler.Add(new Ilce() { ID = 1456, Sehir_ID = 32, Isim = "KEÇİBORLU" });
            ilceler.Add(new Ilce() { ID = 1401, Sehir_ID = 32, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1341, Sehir_ID = 32, Isim = "GELENDOST" });
            ilceler.Add(new Ilce() { ID = 1297, Sehir_ID = 32, Isim = "EĞİRDİR" });
            ilceler.Add(new Ilce() { ID = 1154, Sehir_ID = 32, Isim = "ATABEY" });
            ilceler.Add(new Ilce() { ID = 2067, Sehir_ID = 33, Isim = "YENİŞEHİR" });
            ilceler.Add(new Ilce() { ID = 2066, Sehir_ID = 33, Isim = "TOROSLAR" });
            ilceler.Add(new Ilce() { ID = 2065, Sehir_ID = 33, Isim = "MEZİTLİ" });
            ilceler.Add(new Ilce() { ID = 2064, Sehir_ID = 33, Isim = "AKDENİZ" });
            ilceler.Add(new Ilce() { ID = 1892, Sehir_ID = 33, Isim = "ÇAMLIYAYLA" });
            ilceler.Add(new Ilce() { ID = 1779, Sehir_ID = 33, Isim = "BOZYAZI" });
            ilceler.Add(new Ilce() { ID = 1766, Sehir_ID = 33, Isim = "AYDINCIK" });
            ilceler.Add(new Ilce() { ID = 1665, Sehir_ID = 33, Isim = "TARSUS" });
            ilceler.Add(new Ilce() { ID = 1621, Sehir_ID = 33, Isim = "SİLİFKE" });
            ilceler.Add(new Ilce() { ID = 1536, Sehir_ID = 33, Isim = "MUT" });
            ilceler.Add(new Ilce() { ID = 1402, Sehir_ID = 33, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1366, Sehir_ID = 33, Isim = "GÜLNAR" });
            ilceler.Add(new Ilce() { ID = 1311, Sehir_ID = 33, Isim = "ERDEMLİ" });
            ilceler.Add(new Ilce() { ID = 1135, Sehir_ID = 33, Isim = "ANAMUR" });
            ilceler.Add(new Ilce() { ID = 99157, Sehir_ID = 34, Isim = "İstanbul Havalimanı" });
            ilceler.Add(new Ilce() { ID = 99136, Sehir_ID = 34, Isim = "Atatürk Havalimanı" });
            ilceler.Add(new Ilce() { ID = 99102, Sehir_ID = 34, Isim = "Sabiha Gökçen Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2055, Sehir_ID = 34, Isim = "SULTANGAZİ" });
            ilceler.Add(new Ilce() { ID = 2054, Sehir_ID = 34, Isim = "SANCAKTEPE" });
            ilceler.Add(new Ilce() { ID = 2053, Sehir_ID = 34, Isim = "ESENYURT" });
            ilceler.Add(new Ilce() { ID = 2052, Sehir_ID = 34, Isim = "ÇEKMEKÖY" });
            ilceler.Add(new Ilce() { ID = 2051, Sehir_ID = 34, Isim = "BEYLİKDÜZÜ" });
            ilceler.Add(new Ilce() { ID = 2050, Sehir_ID = 34, Isim = "BAŞAKŞEHİR" });
            ilceler.Add(new Ilce() { ID = 2049, Sehir_ID = 34, Isim = "ATAŞEHİR" });
            ilceler.Add(new Ilce() { ID = 2048, Sehir_ID = 34, Isim = "ARNAVUTKÖY" });
            ilceler.Add(new Ilce() { ID = 2016, Sehir_ID = 34, Isim = "ESENLER" });
            ilceler.Add(new Ilce() { ID = 2015, Sehir_ID = 34, Isim = "TUZLA" });
            ilceler.Add(new Ilce() { ID = 2014, Sehir_ID = 34, Isim = "SULTANBEYLİ" });
            ilceler.Add(new Ilce() { ID = 2012, Sehir_ID = 34, Isim = "MALTEPE" });
            ilceler.Add(new Ilce() { ID = 2010, Sehir_ID = 34, Isim = "GÜNGÖREN" });
            ilceler.Add(new Ilce() { ID = 2005, Sehir_ID = 34, Isim = "BAHÇELİEVLER" });
            ilceler.Add(new Ilce() { ID = 2004, Sehir_ID = 34, Isim = "BAĞCILAR" });
            ilceler.Add(new Ilce() { ID = 2003, Sehir_ID = 34, Isim = "AVCILAR" });
            ilceler.Add(new Ilce() { ID = 1886, Sehir_ID = 34, Isim = "BAYRAMPAŞA" });
            ilceler.Add(new Ilce() { ID = 1852, Sehir_ID = 34, Isim = "ÜMRANİYE" });
            ilceler.Add(new Ilce() { ID = 1835, Sehir_ID = 34, Isim = "PENDİK" });
            ilceler.Add(new Ilce() { ID = 1823, Sehir_ID = 34, Isim = "KÜÇÜKÇEKMECE" });
            ilceler.Add(new Ilce() { ID = 1810, Sehir_ID = 34, Isim = "KAĞITHANE" });
            ilceler.Add(new Ilce() { ID = 1782, Sehir_ID = 34, Isim = "BÜYÜKÇEKMECE" });
            ilceler.Add(new Ilce() { ID = 1739, Sehir_ID = 34, Isim = "ZEYTİNBURNU" });
            ilceler.Add(new Ilce() { ID = 1708, Sehir_ID = 34, Isim = "ÜSKÜDAR" });
            ilceler.Add(new Ilce() { ID = 1663, Sehir_ID = 34, Isim = "ŞİŞLİ" });
            ilceler.Add(new Ilce() { ID = 1659, Sehir_ID = 34, Isim = "ŞİLE" });
            ilceler.Add(new Ilce() { ID = 1622, Sehir_ID = 34, Isim = "SİLİVRİ" });
            ilceler.Add(new Ilce() { ID = 1604, Sehir_ID = 34, Isim = "SARIYER" });
            ilceler.Add(new Ilce() { ID = 1449, Sehir_ID = 34, Isim = "KARTAL" });
            ilceler.Add(new Ilce() { ID = 1421, Sehir_ID = 34, Isim = "KADIKÖY" });
            ilceler.Add(new Ilce() { ID = 1336, Sehir_ID = 34, Isim = "GAZİOSMANPAŞA" });
            ilceler.Add(new Ilce() { ID = 1327, Sehir_ID = 34, Isim = "FATİH" });
            ilceler.Add(new Ilce() { ID = 1325, Sehir_ID = 34, Isim = "EYÜPSULTAN" });
            ilceler.Add(new Ilce() { ID = 1305, Sehir_ID = 34, Isim = "EMİNÖNÜ" });
            ilceler.Add(new Ilce() { ID = 1237, Sehir_ID = 34, Isim = "ÇATALCA" });
            ilceler.Add(new Ilce() { ID = 1186, Sehir_ID = 34, Isim = "BEYOĞLU" });
            ilceler.Add(new Ilce() { ID = 1185, Sehir_ID = 34, Isim = "BEYKOZ" });
            ilceler.Add(new Ilce() { ID = 1183, Sehir_ID = 34, Isim = "BEŞİKTAŞ" });
            ilceler.Add(new Ilce() { ID = 1166, Sehir_ID = 34, Isim = "BAKIRKÖY" });
            ilceler.Add(new Ilce() { ID = 1103, Sehir_ID = 34, Isim = "ADALAR" });
            ilceler.Add(new Ilce() { ID = 99164, Sehir_ID = 35, Isim = "Adnan Menderes Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2057, Sehir_ID = 35, Isim = "KARABAĞLAR" });
            ilceler.Add(new Ilce() { ID = 2056, Sehir_ID = 35, Isim = "BAYRAKLI" });
            ilceler.Add(new Ilce() { ID = 2018, Sehir_ID = 35, Isim = "GÜZELBAHÇE" });
            ilceler.Add(new Ilce() { ID = 2013, Sehir_ID = 35, Isim = "NARLIDERE" });
            ilceler.Add(new Ilce() { ID = 2009, Sehir_ID = 35, Isim = "GAZİEMİR" });
            ilceler.Add(new Ilce() { ID = 2007, Sehir_ID = 35, Isim = "ÇİĞLİ" });
            ilceler.Add(new Ilce() { ID = 2006, Sehir_ID = 35, Isim = "BALÇOVA" });
            ilceler.Add(new Ilce() { ID = 1826, Sehir_ID = 35, Isim = "MENDERES" });
            ilceler.Add(new Ilce() { ID = 1819, Sehir_ID = 35, Isim = "KONAK" });
            ilceler.Add(new Ilce() { ID = 1780, Sehir_ID = 35, Isim = "BUCA" });
            ilceler.Add(new Ilce() { ID = 1776, Sehir_ID = 35, Isim = "BEYDAĞ" });
            ilceler.Add(new Ilce() { ID = 1703, Sehir_ID = 35, Isim = "URLA" });
            ilceler.Add(new Ilce() { ID = 1682, Sehir_ID = 35, Isim = "TORBALI" });
            ilceler.Add(new Ilce() { ID = 1677, Sehir_ID = 35, Isim = "TİRE" });
            ilceler.Add(new Ilce() { ID = 1612, Sehir_ID = 35, Isim = "SELÇUK" });
            ilceler.Add(new Ilce() { ID = 1611, Sehir_ID = 35, Isim = "SEFERİHİSAR" });
            ilceler.Add(new Ilce() { ID = 1563, Sehir_ID = 35, Isim = "ÖDEMİŞ" });
            ilceler.Add(new Ilce() { ID = 1521, Sehir_ID = 35, Isim = "MENEMEN" });
            ilceler.Add(new Ilce() { ID = 1477, Sehir_ID = 35, Isim = "KİRAZ" });
            ilceler.Add(new Ilce() { ID = 1467, Sehir_ID = 35, Isim = "KINIK" });
            ilceler.Add(new Ilce() { ID = 1461, Sehir_ID = 35, Isim = "KEMALPAŞA" });
            ilceler.Add(new Ilce() { ID = 1448, Sehir_ID = 35, Isim = "KARŞIYAKA" });
            ilceler.Add(new Ilce() { ID = 1432, Sehir_ID = 35, Isim = "KARABURUN" });
            ilceler.Add(new Ilce() { ID = 1334, Sehir_ID = 35, Isim = "FOÇA" });
            ilceler.Add(new Ilce() { ID = 1280, Sehir_ID = 35, Isim = "DİKİLİ" });
            ilceler.Add(new Ilce() { ID = 1251, Sehir_ID = 35, Isim = "ÇEŞME" });
            ilceler.Add(new Ilce() { ID = 1203, Sehir_ID = 35, Isim = "BORNOVA" });
            ilceler.Add(new Ilce() { ID = 1181, Sehir_ID = 35, Isim = "BERGAMA" });
            ilceler.Add(new Ilce() { ID = 1178, Sehir_ID = 35, Isim = "BAYINDIR" });
            ilceler.Add(new Ilce() { ID = 1128, Sehir_ID = 35, Isim = "ALİAĞA" });
            ilceler.Add(new Ilce() { ID = 99113, Sehir_ID = 36, Isim = "Kars Harakani Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1756, Sehir_ID = 36, Isim = "AKYAKA" });
            ilceler.Add(new Ilce() { ID = 1645, Sehir_ID = 36, Isim = "SUSUZ" });
            ilceler.Add(new Ilce() { ID = 1614, Sehir_ID = 36, Isim = "SELİM" });
            ilceler.Add(new Ilce() { ID = 1601, Sehir_ID = 36, Isim = "SARIKAMIŞ" });
            ilceler.Add(new Ilce() { ID = 1447, Sehir_ID = 36, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1424, Sehir_ID = 36, Isim = "KAĞIZMAN" });
            ilceler.Add(new Ilce() { ID = 1279, Sehir_ID = 36, Isim = "DİGOR" });
            ilceler.Add(new Ilce() { ID = 1149, Sehir_ID = 36, Isim = "ARPAÇAY" });
            ilceler.Add(new Ilce() { ID = 99154, Sehir_ID = 37, Isim = "Kastamonu Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1984, Sehir_ID = 37, Isim = "SEYDİLER" });
            ilceler.Add(new Ilce() { ID = 1940, Sehir_ID = 37, Isim = "HANÖNÜ" });
            ilceler.Add(new Ilce() { ID = 1915, Sehir_ID = 37, Isim = "DOĞANYURT" });
            ilceler.Add(new Ilce() { ID = 1867, Sehir_ID = 37, Isim = "AĞLI" });
            ilceler.Add(new Ilce() { ID = 1845, Sehir_ID = 37, Isim = "ŞENPAZAR" });
            ilceler.Add(new Ilce() { ID = 1836, Sehir_ID = 37, Isim = "PINARBAŞI" });
            ilceler.Add(new Ilce() { ID = 1805, Sehir_ID = 37, Isim = "İHSANGAZİ" });
            ilceler.Add(new Ilce() { ID = 1685, Sehir_ID = 37, Isim = "TOSYA" });
            ilceler.Add(new Ilce() { ID = 1666, Sehir_ID = 37, Isim = "TAŞKÖPRÜ" });
            ilceler.Add(new Ilce() { ID = 1499, Sehir_ID = 37, Isim = "KÜRE" });
            ilceler.Add(new Ilce() { ID = 1450, Sehir_ID = 37, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1410, Sehir_ID = 37, Isim = "İNEBOLU" });
            ilceler.Add(new Ilce() { ID = 1277, Sehir_ID = 37, Isim = "DEVREKANİ" });
            ilceler.Add(new Ilce() { ID = 1264, Sehir_ID = 37, Isim = "DADAY" });
            ilceler.Add(new Ilce() { ID = 1238, Sehir_ID = 37, Isim = "ÇATALZEYTİN" });
            ilceler.Add(new Ilce() { ID = 1221, Sehir_ID = 37, Isim = "CİDE" });
            ilceler.Add(new Ilce() { ID = 1208, Sehir_ID = 37, Isim = "BOZKURT" });
            ilceler.Add(new Ilce() { ID = 1162, Sehir_ID = 37, Isim = "AZDAVAY" });
            ilceler.Add(new Ilce() { ID = 1140, Sehir_ID = 37, Isim = "ARAÇ" });
            ilceler.Add(new Ilce() { ID = 1101, Sehir_ID = 37, Isim = "ABANA" });
            ilceler.Add(new Ilce() { ID = 99103, Sehir_ID = 38, Isim = "Erkilet Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1978, Sehir_ID = 38, Isim = "ÖZVATAN" });
            ilceler.Add(new Ilce() { ID = 1936, Sehir_ID = 38, Isim = "HACILAR" });
            ilceler.Add(new Ilce() { ID = 1864, Sehir_ID = 38, Isim = "MELİKGAZİ" });
            ilceler.Add(new Ilce() { ID = 1863, Sehir_ID = 38, Isim = "KOCASİNAN" });
            ilceler.Add(new Ilce() { ID = 1846, Sehir_ID = 38, Isim = "TALAS" });
            ilceler.Add(new Ilce() { ID = 1752, Sehir_ID = 38, Isim = "AKKIŞLA" });
            ilceler.Add(new Ilce() { ID = 1727, Sehir_ID = 38, Isim = "YEŞİLHİSAR" });
            ilceler.Add(new Ilce() { ID = 1715, Sehir_ID = 38, Isim = "YAHYALI" });
            ilceler.Add(new Ilce() { ID = 1680, Sehir_ID = 38, Isim = "TOMARZA" });
            ilceler.Add(new Ilce() { ID = 1605, Sehir_ID = 38, Isim = "SARIZ" });
            ilceler.Add(new Ilce() { ID = 1603, Sehir_ID = 38, Isim = "SARIOĞLAN" });
            ilceler.Add(new Ilce() { ID = 1576, Sehir_ID = 38, Isim = "PINARBAŞI" });
            ilceler.Add(new Ilce() { ID = 1409, Sehir_ID = 38, Isim = "İNCESU" });
            ilceler.Add(new Ilce() { ID = 1330, Sehir_ID = 38, Isim = "FELAHİYE" });
            ilceler.Add(new Ilce() { ID = 1275, Sehir_ID = 38, Isim = "DEVELİ" });
            ilceler.Add(new Ilce() { ID = 1218, Sehir_ID = 38, Isim = "BÜNYAN" });
            ilceler.Add(new Ilce() { ID = 1714, Sehir_ID = 39, Isim = "VİZE" });
            ilceler.Add(new Ilce() { ID = 1577, Sehir_ID = 39, Isim = "PINARHİSAR" });
            ilceler.Add(new Ilce() { ID = 1572, Sehir_ID = 39, Isim = "PEHLİVANKÖY" });
            ilceler.Add(new Ilce() { ID = 1505, Sehir_ID = 39, Isim = "LÜLEBURGAZ" });
            ilceler.Add(new Ilce() { ID = 1480, Sehir_ID = 39, Isim = "KOFÇAZ" });
            ilceler.Add(new Ilce() { ID = 1471, Sehir_ID = 39, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1270, Sehir_ID = 39, Isim = "DEMİRKÖY" });
            ilceler.Add(new Ilce() { ID = 1163, Sehir_ID = 39, Isim = "BABAESKİ" });
            ilceler.Add(new Ilce() { ID = 1890, Sehir_ID = 40, Isim = "BOZTEPE" });
            ilceler.Add(new Ilce() { ID = 1869, Sehir_ID = 40, Isim = "AKÇAKENT" });
            ilceler.Add(new Ilce() { ID = 1754, Sehir_ID = 40, Isim = "AKPINAR" });
            ilceler.Add(new Ilce() { ID = 1529, Sehir_ID = 40, Isim = "MUCUR" });
            ilceler.Add(new Ilce() { ID = 1472, Sehir_ID = 40, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1429, Sehir_ID = 40, Isim = "KAMAN" });
            ilceler.Add(new Ilce() { ID = 1254, Sehir_ID = 40, Isim = "ÇİÇEKDAĞI" });
            ilceler.Add(new Ilce() { ID = 99155, Sehir_ID = 41, Isim = "Cengiz Topel Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2063, Sehir_ID = 41, Isim = "KARTEPE" });
            ilceler.Add(new Ilce() { ID = 2062, Sehir_ID = 41, Isim = "İZMİT" });
            ilceler.Add(new Ilce() { ID = 2061, Sehir_ID = 41, Isim = "DİLOVASI" });
            ilceler.Add(new Ilce() { ID = 2060, Sehir_ID = 41, Isim = "DARICA" });
            ilceler.Add(new Ilce() { ID = 2059, Sehir_ID = 41, Isim = "ÇAYIROVA" });
            ilceler.Add(new Ilce() { ID = 2058, Sehir_ID = 41, Isim = "BAŞİSKELE" });
            ilceler.Add(new Ilce() { ID = 2030, Sehir_ID = 41, Isim = "DERİNCE" });
            ilceler.Add(new Ilce() { ID = 1821, Sehir_ID = 41, Isim = "KÖRFEZ" });
            ilceler.Add(new Ilce() { ID = 1478, Sehir_ID = 41, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1440, Sehir_ID = 41, Isim = "KARAMÜRSEL" });
            ilceler.Add(new Ilce() { ID = 1430, Sehir_ID = 41, Isim = "KANDIRA" });
            ilceler.Add(new Ilce() { ID = 1355, Sehir_ID = 41, Isim = "GÖLCÜK" });
            ilceler.Add(new Ilce() { ID = 1338, Sehir_ID = 41, Isim = "GEBZE" });
            ilceler.Add(new Ilce() { ID = 99104, Sehir_ID = 42, Isim = "Konya Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1994, Sehir_ID = 42, Isim = "YALIHÜYÜK" });
            ilceler.Add(new Ilce() { ID = 1990, Sehir_ID = 42, Isim = "TUZLUKÇU" });
            ilceler.Add(new Ilce() { ID = 1937, Sehir_ID = 42, Isim = "HALKAPINAR" });
            ilceler.Add(new Ilce() { ID = 1933, Sehir_ID = 42, Isim = "GÜNEYSINIR" });
            ilceler.Add(new Ilce() { ID = 1920, Sehir_ID = 42, Isim = "EMİRGAZİ" });
            ilceler.Add(new Ilce() { ID = 1907, Sehir_ID = 42, Isim = "DERBENT" });
            ilceler.Add(new Ilce() { ID = 1902, Sehir_ID = 42, Isim = "ÇELTİK" });
            ilceler.Add(new Ilce() { ID = 1868, Sehir_ID = 42, Isim = "AHIRLI" });
            ilceler.Add(new Ilce() { ID = 1848, Sehir_ID = 42, Isim = "TAŞKENT" });
            ilceler.Add(new Ilce() { ID = 1839, Sehir_ID = 42, Isim = "SELÇUKLU" });
            ilceler.Add(new Ilce() { ID = 1827, Sehir_ID = 42, Isim = "MERAM" });
            ilceler.Add(new Ilce() { ID = 1814, Sehir_ID = 42, Isim = "KARATAY" });
            ilceler.Add(new Ilce() { ID = 1804, Sehir_ID = 42, Isim = "HÜYÜK" });
            ilceler.Add(new Ilce() { ID = 1789, Sehir_ID = 42, Isim = "DEREBUCAK" });
            ilceler.Add(new Ilce() { ID = 1760, Sehir_ID = 42, Isim = "ALTINEKİN" });
            ilceler.Add(new Ilce() { ID = 1753, Sehir_ID = 42, Isim = "AKÖREN" });
            ilceler.Add(new Ilce() { ID = 1735, Sehir_ID = 42, Isim = "YUNAK" });
            ilceler.Add(new Ilce() { ID = 1617, Sehir_ID = 42, Isim = "SEYDİŞEHİR" });
            ilceler.Add(new Ilce() { ID = 1598, Sehir_ID = 42, Isim = "SARAYÖNÜ" });
            ilceler.Add(new Ilce() { ID = 1491, Sehir_ID = 42, Isim = "KULU" });
            ilceler.Add(new Ilce() { ID = 1441, Sehir_ID = 42, Isim = "KARAPINAR" });
            ilceler.Add(new Ilce() { ID = 1422, Sehir_ID = 42, Isim = "KADINHANI" });
            ilceler.Add(new Ilce() { ID = 1400, Sehir_ID = 42, Isim = "ILGIN" });
            ilceler.Add(new Ilce() { ID = 1375, Sehir_ID = 42, Isim = "HADİM" });
            ilceler.Add(new Ilce() { ID = 1312, Sehir_ID = 42, Isim = "EREĞLİ" });
            ilceler.Add(new Ilce() { ID = 1285, Sehir_ID = 42, Isim = "DOĞANHİSAR" });
            ilceler.Add(new Ilce() { ID = 1262, Sehir_ID = 42, Isim = "ÇUMRA" });
            ilceler.Add(new Ilce() { ID = 1222, Sehir_ID = 42, Isim = "CİHANBEYLİ" });
            ilceler.Add(new Ilce() { ID = 1207, Sehir_ID = 42, Isim = "BOZKIR" });
            ilceler.Add(new Ilce() { ID = 1188, Sehir_ID = 42, Isim = "BEYŞEHİR" });
            ilceler.Add(new Ilce() { ID = 1122, Sehir_ID = 42, Isim = "AKŞEHİR" });
            ilceler.Add(new Ilce() { ID = 99165, Sehir_ID = 43, Isim = "Zafer Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1979, Sehir_ID = 43, Isim = "PAZARLAR" });
            ilceler.Add(new Ilce() { ID = 1898, Sehir_ID = 43, Isim = "ÇAVDARHİSAR" });
            ilceler.Add(new Ilce() { ID = 1843, Sehir_ID = 43, Isim = "ŞAPHANE" });
            ilceler.Add(new Ilce() { ID = 1802, Sehir_ID = 43, Isim = "HİSARCIK" });
            ilceler.Add(new Ilce() { ID = 1790, Sehir_ID = 43, Isim = "DUMLUPINAR" });
            ilceler.Add(new Ilce() { ID = 1764, Sehir_ID = 43, Isim = "ASLANAPA" });
            ilceler.Add(new Ilce() { ID = 1671, Sehir_ID = 43, Isim = "TAVŞANLI" });
            ilceler.Add(new Ilce() { ID = 1625, Sehir_ID = 43, Isim = "SİMAV" });
            ilceler.Add(new Ilce() { ID = 1500, Sehir_ID = 43, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1339, Sehir_ID = 43, Isim = "GEDİZ" });
            ilceler.Add(new Ilce() { ID = 1304, Sehir_ID = 43, Isim = "EMET" });
            ilceler.Add(new Ilce() { ID = 1288, Sehir_ID = 43, Isim = "DOMANİÇ" });
            ilceler.Add(new Ilce() { ID = 1132, Sehir_ID = 43, Isim = "ALTINTAŞ" });
            ilceler.Add(new Ilce() { ID = 99137, Sehir_ID = 44, Isim = "Erhaç Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1995, Sehir_ID = 44, Isim = "YAZIHAN" });
            ilceler.Add(new Ilce() { ID = 1969, Sehir_ID = 44, Isim = "KULUNCAK" });
            ilceler.Add(new Ilce() { ID = 1953, Sehir_ID = 44, Isim = "KALE" });
            ilceler.Add(new Ilce() { ID = 1914, Sehir_ID = 44, Isim = "DOĞANYOL" });
            ilceler.Add(new Ilce() { ID = 1772, Sehir_ID = 44, Isim = "BATTALGAZİ" });
            ilceler.Add(new Ilce() { ID = 1729, Sehir_ID = 44, Isim = "YEŞİLYURT" });
            ilceler.Add(new Ilce() { ID = 1582, Sehir_ID = 44, Isim = "PÜTÜRGE" });
            ilceler.Add(new Ilce() { ID = 1509, Sehir_ID = 44, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1390, Sehir_ID = 44, Isim = "HEKİMHAN" });
            ilceler.Add(new Ilce() { ID = 1286, Sehir_ID = 44, Isim = "DOĞANŞEHİR" });
            ilceler.Add(new Ilce() { ID = 1265, Sehir_ID = 44, Isim = "DARENDE" });
            ilceler.Add(new Ilce() { ID = 1148, Sehir_ID = 44, Isim = "ARGUVAN" });
            ilceler.Add(new Ilce() { ID = 1143, Sehir_ID = 44, Isim = "ARAPGİR" });
            ilceler.Add(new Ilce() { ID = 1114, Sehir_ID = 44, Isim = "AKÇADAĞ" });
            ilceler.Add(new Ilce() { ID = 2087, Sehir_ID = 45, Isim = "YUNUSEMRE" });
            ilceler.Add(new Ilce() { ID = 2086, Sehir_ID = 45, Isim = "ŞEHZADELER" });
            ilceler.Add(new Ilce() { ID = 1965, Sehir_ID = 45, Isim = "KÖPRÜBAŞI" });
            ilceler.Add(new Ilce() { ID = 1793, Sehir_ID = 45, Isim = "GÖLMARMARA" });
            ilceler.Add(new Ilce() { ID = 1751, Sehir_ID = 45, Isim = "AHMETLİ" });
            ilceler.Add(new Ilce() { ID = 1689, Sehir_ID = 45, Isim = "TURGUTLU" });
            ilceler.Add(new Ilce() { ID = 1634, Sehir_ID = 45, Isim = "SOMA" });
            ilceler.Add(new Ilce() { ID = 1613, Sehir_ID = 45, Isim = "SELENDİ" });
            ilceler.Add(new Ilce() { ID = 1606, Sehir_ID = 45, Isim = "SARUHANLI" });
            ilceler.Add(new Ilce() { ID = 1600, Sehir_ID = 45, Isim = "SARIGÖL" });
            ilceler.Add(new Ilce() { ID = 1590, Sehir_ID = 45, Isim = "SALİHLİ" });
            ilceler.Add(new Ilce() { ID = 1513, Sehir_ID = 45, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1489, Sehir_ID = 45, Isim = "KULA" });
            ilceler.Add(new Ilce() { ID = 1470, Sehir_ID = 45, Isim = "KIRKAĞAÇ" });
            ilceler.Add(new Ilce() { ID = 1362, Sehir_ID = 45, Isim = "GÖRDES" });
            ilceler.Add(new Ilce() { ID = 1269, Sehir_ID = 45, Isim = "DEMİRCİ" });
            ilceler.Add(new Ilce() { ID = 1127, Sehir_ID = 45, Isim = "ALAŞEHİR" });
            ilceler.Add(new Ilce() { ID = 1118, Sehir_ID = 45, Isim = "AKHİSAR" });
            ilceler.Add(new Ilce() { ID = 99145, Sehir_ID = 46, Isim = "Kahramanmaraş Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2085, Sehir_ID = 46, Isim = "ONİKİŞUBAT" });
            ilceler.Add(new Ilce() { ID = 2084, Sehir_ID = 46, Isim = "DULKADİROĞLU" });
            ilceler.Add(new Ilce() { ID = 1975, Sehir_ID = 46, Isim = "NURHAK" });
            ilceler.Add(new Ilce() { ID = 1919, Sehir_ID = 46, Isim = "EKİNÖZÜ" });
            ilceler.Add(new Ilce() { ID = 1785, Sehir_ID = 46, Isim = "ÇAĞLAYANCERİT" });
            ilceler.Add(new Ilce() { ID = 1694, Sehir_ID = 46, Isim = "TÜRKOĞLU" });
            ilceler.Add(new Ilce() { ID = 1570, Sehir_ID = 46, Isim = "PAZARCIK" });
            ilceler.Add(new Ilce() { ID = 1515, Sehir_ID = 46, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1353, Sehir_ID = 46, Isim = "GÖKSUN" });
            ilceler.Add(new Ilce() { ID = 1299, Sehir_ID = 46, Isim = "ELBİSTAN" });
            ilceler.Add(new Ilce() { ID = 1136, Sehir_ID = 46, Isim = "ANDIRIN" });
            ilceler.Add(new Ilce() { ID = 1107, Sehir_ID = 46, Isim = "AFŞİN" });
            ilceler.Add(new Ilce() { ID = 99114, Sehir_ID = 47, Isim = "Mardin Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2088, Sehir_ID = 47, Isim = "ARTUKLU" });
            ilceler.Add(new Ilce() { ID = 2002, Sehir_ID = 47, Isim = "YEŞİLLİ" });
            ilceler.Add(new Ilce() { ID = 1787, Sehir_ID = 47, Isim = "DARGEÇİT" });
            ilceler.Add(new Ilce() { ID = 1609, Sehir_ID = 47, Isim = "SAVUR" });
            ilceler.Add(new Ilce() { ID = 1564, Sehir_ID = 47, Isim = "ÖMERLİ" });
            ilceler.Add(new Ilce() { ID = 1547, Sehir_ID = 47, Isim = "NUSAYBİN" });
            ilceler.Add(new Ilce() { ID = 1526, Sehir_ID = 47, Isim = "MİDYAT" });
            ilceler.Add(new Ilce() { ID = 1519, Sehir_ID = 47, Isim = "MAZIDAĞI" });
            ilceler.Add(new Ilce() { ID = 1516, Sehir_ID = 47, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1474, Sehir_ID = 47, Isim = "KIZILTEPE" });
            ilceler.Add(new Ilce() { ID = 1273, Sehir_ID = 47, Isim = "DERİK" });
            ilceler.Add(new Ilce() { ID = 99151, Sehir_ID = 48, Isim = "Milas-Bodrum Havalimanı" });
            ilceler.Add(new Ilce() { ID = 99125, Sehir_ID = 48, Isim = "Dalaman Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2090, Sehir_ID = 48, Isim = "SEYDİKEMER" });
            ilceler.Add(new Ilce() { ID = 2089, Sehir_ID = 48, Isim = "MENTEŞE" });
            ilceler.Add(new Ilce() { ID = 1958, Sehir_ID = 48, Isim = "KAVAKLIDERE" });
            ilceler.Add(new Ilce() { ID = 1831, Sehir_ID = 48, Isim = "ORTACA" });
            ilceler.Add(new Ilce() { ID = 1742, Sehir_ID = 48, Isim = "DALAMAN" });
            ilceler.Add(new Ilce() { ID = 1719, Sehir_ID = 48, Isim = "YATAĞAN" });
            ilceler.Add(new Ilce() { ID = 1695, Sehir_ID = 48, Isim = "ULA" });
            ilceler.Add(new Ilce() { ID = 1532, Sehir_ID = 48, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1528, Sehir_ID = 48, Isim = "MİLAS" });
            ilceler.Add(new Ilce() { ID = 1517, Sehir_ID = 48, Isim = "MARMARİS" });
            ilceler.Add(new Ilce() { ID = 1488, Sehir_ID = 48, Isim = "KÖYCEĞİZ" });
            ilceler.Add(new Ilce() { ID = 1331, Sehir_ID = 48, Isim = "FETHİYE" });
            ilceler.Add(new Ilce() { ID = 1266, Sehir_ID = 48, Isim = "DATÇA" });
            ilceler.Add(new Ilce() { ID = 1197, Sehir_ID = 48, Isim = "BODRUM" });
            ilceler.Add(new Ilce() { ID = 99129, Sehir_ID = 49, Isim = "Muş Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1964, Sehir_ID = 49, Isim = "KORKUT" });
            ilceler.Add(new Ilce() { ID = 1801, Sehir_ID = 49, Isim = "HASKÖY" });
            ilceler.Add(new Ilce() { ID = 1711, Sehir_ID = 49, Isim = "VARTO" });
            ilceler.Add(new Ilce() { ID = 1534, Sehir_ID = 49, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1510, Sehir_ID = 49, Isim = "MALAZGİRT" });
            ilceler.Add(new Ilce() { ID = 1213, Sehir_ID = 49, Isim = "BULANIK" });
            ilceler.Add(new Ilce() { ID = 99105, Sehir_ID = 50, Isim = "Nevşehir Kapadokya Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1749, Sehir_ID = 50, Isim = "ACIGÖL" });
            ilceler.Add(new Ilce() { ID = 1707, Sehir_ID = 50, Isim = "ÜRGÜP" });
            ilceler.Add(new Ilce() { ID = 1543, Sehir_ID = 50, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1485, Sehir_ID = 50, Isim = "KOZAKLI" });
            ilceler.Add(new Ilce() { ID = 1374, Sehir_ID = 50, Isim = "HACIBEKTAŞ" });
            ilceler.Add(new Ilce() { ID = 1367, Sehir_ID = 50, Isim = "GÜLŞEHİR" });
            ilceler.Add(new Ilce() { ID = 1274, Sehir_ID = 50, Isim = "DERİNKUYU" });
            ilceler.Add(new Ilce() { ID = 1155, Sehir_ID = 50, Isim = "AVANOS" });
            ilceler.Add(new Ilce() { ID = 1904, Sehir_ID = 51, Isim = "ÇİFTLİK" });
            ilceler.Add(new Ilce() { ID = 1876, Sehir_ID = 51, Isim = "ALTUNHİSAR" });
            ilceler.Add(new Ilce() { ID = 1700, Sehir_ID = 51, Isim = "ULUKIŞLA" });
            ilceler.Add(new Ilce() { ID = 1544, Sehir_ID = 51, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1225, Sehir_ID = 51, Isim = "ÇAMARDI" });
            ilceler.Add(new Ilce() { ID = 1201, Sehir_ID = 51, Isim = "BOR" });
            ilceler.Add(new Ilce() { ID = 99163, Sehir_ID = 52, Isim = "Ordu-Giresun Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2103, Sehir_ID = 52, Isim = "ALTINORDU" });
            ilceler.Add(new Ilce() { ID = 1951, Sehir_ID = 52, Isim = "KABATAŞ" });
            ilceler.Add(new Ilce() { ID = 1950, Sehir_ID = 52, Isim = "KABADÜZ" });
            ilceler.Add(new Ilce() { ID = 1947, Sehir_ID = 52, Isim = "İKİZCE" });
            ilceler.Add(new Ilce() { ID = 1900, Sehir_ID = 52, Isim = "ÇAYBAŞI" });
            ilceler.Add(new Ilce() { ID = 1897, Sehir_ID = 52, Isim = "ÇATALPINAR" });
            ilceler.Add(new Ilce() { ID = 1891, Sehir_ID = 52, Isim = "ÇAMAŞ" });
            ilceler.Add(new Ilce() { ID = 1797, Sehir_ID = 52, Isim = "GÜRGENTEPE" });
            ilceler.Add(new Ilce() { ID = 1795, Sehir_ID = 52, Isim = "GÜLYALI" });
            ilceler.Add(new Ilce() { ID = 1706, Sehir_ID = 52, Isim = "ÜNYE" });
            ilceler.Add(new Ilce() { ID = 1696, Sehir_ID = 52, Isim = "ULUBEY" });
            ilceler.Add(new Ilce() { ID = 1573, Sehir_ID = 52, Isim = "PERŞEMBE" });
            ilceler.Add(new Ilce() { ID = 1552, Sehir_ID = 52, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1525, Sehir_ID = 52, Isim = "MESUDİYE" });
            ilceler.Add(new Ilce() { ID = 1493, Sehir_ID = 52, Isim = "KUMRU" });
            ilceler.Add(new Ilce() { ID = 1482, Sehir_ID = 52, Isim = "KORGAN" });
            ilceler.Add(new Ilce() { ID = 1358, Sehir_ID = 52, Isim = "GÖLKÖY" });
            ilceler.Add(new Ilce() { ID = 1328, Sehir_ID = 52, Isim = "FATSA" });
            ilceler.Add(new Ilce() { ID = 1158, Sehir_ID = 52, Isim = "AYBASTI" });
            ilceler.Add(new Ilce() { ID = 1119, Sehir_ID = 52, Isim = "AKKUŞ" });
            ilceler.Add(new Ilce() { ID = 1949, Sehir_ID = 53, Isim = "İYİDERE" });
            ilceler.Add(new Ilce() { ID = 1943, Sehir_ID = 53, Isim = "HEMŞİN" });
            ilceler.Add(new Ilce() { ID = 1908, Sehir_ID = 53, Isim = "DEREPAZARI" });
            ilceler.Add(new Ilce() { ID = 1796, Sehir_ID = 53, Isim = "GÜNEYSU" });
            ilceler.Add(new Ilce() { ID = 1586, Sehir_ID = 53, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1569, Sehir_ID = 53, Isim = "PAZAR" });
            ilceler.Add(new Ilce() { ID = 1428, Sehir_ID = 53, Isim = "KALKANDERE" });
            ilceler.Add(new Ilce() { ID = 1405, Sehir_ID = 53, Isim = "İKİZDERE" });
            ilceler.Add(new Ilce() { ID = 1332, Sehir_ID = 53, Isim = "FINDIKLI" });
            ilceler.Add(new Ilce() { ID = 1241, Sehir_ID = 53, Isim = "ÇAYELİ" });
            ilceler.Add(new Ilce() { ID = 1228, Sehir_ID = 53, Isim = "ÇAMLIHEMŞİN" });
            ilceler.Add(new Ilce() { ID = 1146, Sehir_ID = 53, Isim = "ARDEŞEN" });
            ilceler.Add(new Ilce() { ID = 2071, Sehir_ID = 54, Isim = "SERDİVAN" });
            ilceler.Add(new Ilce() { ID = 2070, Sehir_ID = 54, Isim = "ERENLER" });
            ilceler.Add(new Ilce() { ID = 2069, Sehir_ID = 54, Isim = "ARİFİYE" });
            ilceler.Add(new Ilce() { ID = 2068, Sehir_ID = 54, Isim = "ADAPAZARI" });
            ilceler.Add(new Ilce() { ID = 1986, Sehir_ID = 54, Isim = "SÖĞÜTLÜ" });
            ilceler.Add(new Ilce() { ID = 1955, Sehir_ID = 54, Isim = "KARAPÜRÇEK" });
            ilceler.Add(new Ilce() { ID = 1925, Sehir_ID = 54, Isim = "FERİZLİ" });
            ilceler.Add(new Ilce() { ID = 1847, Sehir_ID = 54, Isim = "TARAKLI" });
            ilceler.Add(new Ilce() { ID = 1833, Sehir_ID = 54, Isim = "PAMUKOVA" });
            ilceler.Add(new Ilce() { ID = 1818, Sehir_ID = 54, Isim = "KOCAALİ" });
            ilceler.Add(new Ilce() { ID = 1595, Sehir_ID = 54, Isim = "SAPANCA" });
            ilceler.Add(new Ilce() { ID = 1589, Sehir_ID = 54, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1453, Sehir_ID = 54, Isim = "KAYNARCA" });
            ilceler.Add(new Ilce() { ID = 1442, Sehir_ID = 54, Isim = "KARASU" });
            ilceler.Add(new Ilce() { ID = 1391, Sehir_ID = 54, Isim = "HENDEK" });
            ilceler.Add(new Ilce() { ID = 1351, Sehir_ID = 54, Isim = "GEYVE" });
            ilceler.Add(new Ilce() { ID = 1123, Sehir_ID = 54, Isim = "AKYAZI" });
            ilceler.Add(new Ilce() { ID = 99127, Sehir_ID = 55, Isim = "Samsun Çarşamba Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2074, Sehir_ID = 55, Isim = "İLKADIM" });
            ilceler.Add(new Ilce() { ID = 2073, Sehir_ID = 55, Isim = "CANİK" });
            ilceler.Add(new Ilce() { ID = 2072, Sehir_ID = 55, Isim = "ATAKUM" });
            ilceler.Add(new Ilce() { ID = 1993, Sehir_ID = 55, Isim = "YAKAKENT" });
            ilceler.Add(new Ilce() { ID = 1879, Sehir_ID = 55, Isim = "AYVACIK" });
            ilceler.Add(new Ilce() { ID = 1849, Sehir_ID = 55, Isim = "TEKKEKÖY" });
            ilceler.Add(new Ilce() { ID = 1838, Sehir_ID = 55, Isim = "SALIPAZARI" });
            ilceler.Add(new Ilce() { ID = 1830, Sehir_ID = 55, Isim = "19 MAYIS" });
            ilceler.Add(new Ilce() { ID = 1763, Sehir_ID = 55, Isim = "ASARCIK" });
            ilceler.Add(new Ilce() { ID = 1712, Sehir_ID = 55, Isim = "VEZİRKÖPRÜ" });
            ilceler.Add(new Ilce() { ID = 1676, Sehir_ID = 55, Isim = "TERME" });
            ilceler.Add(new Ilce() { ID = 1593, Sehir_ID = 55, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1501, Sehir_ID = 55, Isim = "LADİK" });
            ilceler.Add(new Ilce() { ID = 1452, Sehir_ID = 55, Isim = "KAVAK" });
            ilceler.Add(new Ilce() { ID = 1386, Sehir_ID = 55, Isim = "HAVZA" });
            ilceler.Add(new Ilce() { ID = 1234, Sehir_ID = 55, Isim = "ÇARŞAMBA" });
            ilceler.Add(new Ilce() { ID = 1164, Sehir_ID = 55, Isim = "BAFRA" });
            ilceler.Add(new Ilce() { ID = 1125, Sehir_ID = 55, Isim = "ALAÇAM" });
            ilceler.Add(new Ilce() { ID = 99115, Sehir_ID = 56, Isim = "Siirt Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1878, Sehir_ID = 56, Isim = "TİLLO" });
            ilceler.Add(new Ilce() { ID = 1662, Sehir_ID = 56, Isim = "ŞİRVAN" });
            ilceler.Add(new Ilce() { ID = 1620, Sehir_ID = 56, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1575, Sehir_ID = 56, Isim = "PERVARİ" });
            ilceler.Add(new Ilce() { ID = 1495, Sehir_ID = 56, Isim = "KURTALAN" });
            ilceler.Add(new Ilce() { ID = 1317, Sehir_ID = 56, Isim = "ERUH" });
            ilceler.Add(new Ilce() { ID = 1179, Sehir_ID = 56, Isim = "BAYKAN" });
            ilceler.Add(new Ilce() { ID = 99116, Sehir_ID = 57, Isim = "Sinop Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1981, Sehir_ID = 57, Isim = "SARAYDÜZÜ" });
            ilceler.Add(new Ilce() { ID = 1910, Sehir_ID = 57, Isim = "DİKMEN" });
            ilceler.Add(new Ilce() { ID = 1693, Sehir_ID = 57, Isim = "TÜRKELİ" });
            ilceler.Add(new Ilce() { ID = 1627, Sehir_ID = 57, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1349, Sehir_ID = 57, Isim = "GERZE" });
            ilceler.Add(new Ilce() { ID = 1314, Sehir_ID = 57, Isim = "ERFELEK" });
            ilceler.Add(new Ilce() { ID = 1290, Sehir_ID = 57, Isim = "DURAĞAN" });
            ilceler.Add(new Ilce() { ID = 1204, Sehir_ID = 57, Isim = "BOYABAT" });
            ilceler.Add(new Ilce() { ID = 1156, Sehir_ID = 57, Isim = "AYANCIK" });
            ilceler.Add(new Ilce() { ID = 99117, Sehir_ID = 58, Isim = "Sivas Nuri Demirağ Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1991, Sehir_ID = 58, Isim = "ULAŞ" });
            ilceler.Add(new Ilce() { ID = 1927, Sehir_ID = 58, Isim = "GÖLOVA" });
            ilceler.Add(new Ilce() { ID = 1913, Sehir_ID = 58, Isim = "DOĞANŞAR" });
            ilceler.Add(new Ilce() { ID = 1875, Sehir_ID = 58, Isim = "ALTINYAYLA" });
            ilceler.Add(new Ilce() { ID = 1870, Sehir_ID = 58, Isim = "AKINCILAR" });
            ilceler.Add(new Ilce() { ID = 1738, Sehir_ID = 58, Isim = "ZARA" });
            ilceler.Add(new Ilce() { ID = 1731, Sehir_ID = 58, Isim = "YILDIZELİ" });
            ilceler.Add(new Ilce() { ID = 1650, Sehir_ID = 58, Isim = "ŞARKIŞLA" });
            ilceler.Add(new Ilce() { ID = 1646, Sehir_ID = 58, Isim = "SUŞEHRİ" });
            ilceler.Add(new Ilce() { ID = 1628, Sehir_ID = 58, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1484, Sehir_ID = 58, Isim = "KOYULHİSAR" });
            ilceler.Add(new Ilce() { ID = 1431, Sehir_ID = 58, Isim = "KANGAL" });
            ilceler.Add(new Ilce() { ID = 1407, Sehir_ID = 58, Isim = "İMRANLI" });
            ilceler.Add(new Ilce() { ID = 1376, Sehir_ID = 58, Isim = "HAFİK" });
            ilceler.Add(new Ilce() { ID = 1373, Sehir_ID = 58, Isim = "GÜRÜN" });
            ilceler.Add(new Ilce() { ID = 1342, Sehir_ID = 58, Isim = "GEMEREK" });
            ilceler.Add(new Ilce() { ID = 1282, Sehir_ID = 58, Isim = "DİVRİĞİ" });
            ilceler.Add(new Ilce() { ID = 99119, Sehir_ID = 59, Isim = "Tekirdağ Çorlu Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2096, Sehir_ID = 59, Isim = "SÜLEYMANPAŞA" });
            ilceler.Add(new Ilce() { ID = 2095, Sehir_ID = 59, Isim = "KAPAKLI" });
            ilceler.Add(new Ilce() { ID = 2094, Sehir_ID = 59, Isim = "ERGENE" });
            ilceler.Add(new Ilce() { ID = 1825, Sehir_ID = 59, Isim = "MARMARAEREĞLİSİ" });
            ilceler.Add(new Ilce() { ID = 1673, Sehir_ID = 59, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1652, Sehir_ID = 59, Isim = "ŞARKÖY" });
            ilceler.Add(new Ilce() { ID = 1596, Sehir_ID = 59, Isim = "SARAY" });
            ilceler.Add(new Ilce() { ID = 1538, Sehir_ID = 59, Isim = "MURATLI" });
            ilceler.Add(new Ilce() { ID = 1511, Sehir_ID = 59, Isim = "MALKARA" });
            ilceler.Add(new Ilce() { ID = 1388, Sehir_ID = 59, Isim = "HAYRABOLU" });
            ilceler.Add(new Ilce() { ID = 1258, Sehir_ID = 59, Isim = "ÇORLU" });
            ilceler.Add(new Ilce() { ID = 1250, Sehir_ID = 59, Isim = "ÇERKEZKÖY" });
            ilceler.Add(new Ilce() { ID = 99169, Sehir_ID = 60, Isim = "Tokat Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1987, Sehir_ID = 60, Isim = "SULUSARAY" });
            ilceler.Add(new Ilce() { ID = 1883, Sehir_ID = 60, Isim = "BAŞÇİFTLİK" });
            ilceler.Add(new Ilce() { ID = 1858, Sehir_ID = 60, Isim = "YEŞİLYURT" });
            ilceler.Add(new Ilce() { ID = 1834, Sehir_ID = 60, Isim = "PAZAR" });
            ilceler.Add(new Ilce() { ID = 1740, Sehir_ID = 60, Isim = "ZİLE" });
            ilceler.Add(new Ilce() { ID = 1690, Sehir_ID = 60, Isim = "TURHAL" });
            ilceler.Add(new Ilce() { ID = 1679, Sehir_ID = 60, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1584, Sehir_ID = 60, Isim = "REŞADİYE" });
            ilceler.Add(new Ilce() { ID = 1545, Sehir_ID = 60, Isim = "NİKSAR" });
            ilceler.Add(new Ilce() { ID = 1308, Sehir_ID = 60, Isim = "ERBAA" });
            ilceler.Add(new Ilce() { ID = 1151, Sehir_ID = 60, Isim = "ARTOVA" });
            ilceler.Add(new Ilce() { ID = 1129, Sehir_ID = 60, Isim = "ALMUS" });
            ilceler.Add(new Ilce() { ID = 99152, Sehir_ID = 61, Isim = "Trabzon Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2097, Sehir_ID = 61, Isim = "ORTAHİSAR" });
            ilceler.Add(new Ilce() { ID = 1966, Sehir_ID = 61, Isim = "KÖPRÜBAŞI" });
            ilceler.Add(new Ilce() { ID = 1942, Sehir_ID = 61, Isim = "HAYRAT" });
            ilceler.Add(new Ilce() { ID = 1917, Sehir_ID = 61, Isim = "DÜZKÖY" });
            ilceler.Add(new Ilce() { ID = 1909, Sehir_ID = 61, Isim = "DERNEKPAZARI" });
            ilceler.Add(new Ilce() { ID = 1896, Sehir_ID = 61, Isim = "ÇARŞIBAŞI" });
            ilceler.Add(new Ilce() { ID = 1842, Sehir_ID = 61, Isim = "ŞALPAZARI" });
            ilceler.Add(new Ilce() { ID = 1775, Sehir_ID = 61, Isim = "BEŞİKDÜZÜ" });
            ilceler.Add(new Ilce() { ID = 1732, Sehir_ID = 61, Isim = "YOMRA" });
            ilceler.Add(new Ilce() { ID = 1709, Sehir_ID = 61, Isim = "VAKFIKEBİR" });
            ilceler.Add(new Ilce() { ID = 1686, Sehir_ID = 61, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1681, Sehir_ID = 61, Isim = "TONYA" });
            ilceler.Add(new Ilce() { ID = 1647, Sehir_ID = 61, Isim = "SÜRMENE" });
            ilceler.Add(new Ilce() { ID = 1548, Sehir_ID = 61, Isim = "OF" });
            ilceler.Add(new Ilce() { ID = 1507, Sehir_ID = 61, Isim = "MAÇKA" });
            ilceler.Add(new Ilce() { ID = 1244, Sehir_ID = 61, Isim = "ÇAYKARA" });
            ilceler.Add(new Ilce() { ID = 1150, Sehir_ID = 61, Isim = "ARSİN" });
            ilceler.Add(new Ilce() { ID = 1141, Sehir_ID = 61, Isim = "ARAKLI" });
            ilceler.Add(new Ilce() { ID = 1113, Sehir_ID = 61, Isim = "AKÇAABAT" });
            ilceler.Add(new Ilce() { ID = 1688, Sehir_ID = 62, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1581, Sehir_ID = 62, Isim = "PÜLÜMÜR" });
            ilceler.Add(new Ilce() { ID = 1574, Sehir_ID = 62, Isim = "PERTEK" });
            ilceler.Add(new Ilce() { ID = 1562, Sehir_ID = 62, Isim = "OVACIK" });
            ilceler.Add(new Ilce() { ID = 1541, Sehir_ID = 62, Isim = "NAZIMİYE" });
            ilceler.Add(new Ilce() { ID = 1518, Sehir_ID = 62, Isim = "MAZGİRT" });
            ilceler.Add(new Ilce() { ID = 1397, Sehir_ID = 62, Isim = "HOZAT" });
            ilceler.Add(new Ilce() { ID = 1247, Sehir_ID = 62, Isim = "ÇEMİŞGEZEK" });
            ilceler.Add(new Ilce() { ID = 99138, Sehir_ID = 63, Isim = "Şanlıurfa GAP Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2093, Sehir_ID = 63, Isim = "KARAKÖPRÜ" });
            ilceler.Add(new Ilce() { ID = 2092, Sehir_ID = 63, Isim = "HALİLİYE" });
            ilceler.Add(new Ilce() { ID = 2091, Sehir_ID = 63, Isim = "EYYÜBİYE" });
            ilceler.Add(new Ilce() { ID = 1800, Sehir_ID = 63, Isim = "HARRAN" });
            ilceler.Add(new Ilce() { ID = 1713, Sehir_ID = 63, Isim = "VİRANŞEHİR" });
            ilceler.Add(new Ilce() { ID = 1702, Sehir_ID = 63, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1643, Sehir_ID = 63, Isim = "SURUÇ" });
            ilceler.Add(new Ilce() { ID = 1630, Sehir_ID = 63, Isim = "SİVEREK" });
            ilceler.Add(new Ilce() { ID = 1393, Sehir_ID = 63, Isim = "HİLVAN" });
            ilceler.Add(new Ilce() { ID = 1378, Sehir_ID = 63, Isim = "HALFETİ" });
            ilceler.Add(new Ilce() { ID = 1220, Sehir_ID = 63, Isim = "CEYLANPINAR" });
            ilceler.Add(new Ilce() { ID = 1209, Sehir_ID = 63, Isim = "BOZOVA" });
            ilceler.Add(new Ilce() { ID = 1194, Sehir_ID = 63, Isim = "BİRECİK" });
            ilceler.Add(new Ilce() { ID = 1115, Sehir_ID = 63, Isim = "AKÇAKALE" });
            ilceler.Add(new Ilce() { ID = 99120, Sehir_ID = 64, Isim = "Uşak Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1704, Sehir_ID = 64, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1697, Sehir_ID = 64, Isim = "ULUBEY" });
            ilceler.Add(new Ilce() { ID = 1629, Sehir_ID = 64, Isim = "SİVASLI" });
            ilceler.Add(new Ilce() { ID = 1436, Sehir_ID = 64, Isim = "KARAHALLI" });
            ilceler.Add(new Ilce() { ID = 1323, Sehir_ID = 64, Isim = "EŞME" });
            ilceler.Add(new Ilce() { ID = 1170, Sehir_ID = 64, Isim = "BANAZ" });
            ilceler.Add(new Ilce() { ID = 99146, Sehir_ID = 65, Isim = "Ferit Melen Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2099, Sehir_ID = 65, Isim = "TUŞBA" });
            ilceler.Add(new Ilce() { ID = 2098, Sehir_ID = 65, Isim = "İPEKYOLU" });
            ilceler.Add(new Ilce() { ID = 1980, Sehir_ID = 65, Isim = "SARAY" });
            ilceler.Add(new Ilce() { ID = 1918, Sehir_ID = 65, Isim = "EDREMİT" });
            ilceler.Add(new Ilce() { ID = 1786, Sehir_ID = 65, Isim = "ÇALDIRAN" });
            ilceler.Add(new Ilce() { ID = 1770, Sehir_ID = 65, Isim = "BAHÇESARAY" });
            ilceler.Add(new Ilce() { ID = 1710, Sehir_ID = 65, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1565, Sehir_ID = 65, Isim = "ÖZALP" });
            ilceler.Add(new Ilce() { ID = 1533, Sehir_ID = 65, Isim = "MURADİYE" });
            ilceler.Add(new Ilce() { ID = 1372, Sehir_ID = 65, Isim = "GÜRPINAR" });
            ilceler.Add(new Ilce() { ID = 1350, Sehir_ID = 65, Isim = "GEVAŞ" });
            ilceler.Add(new Ilce() { ID = 1309, Sehir_ID = 65, Isim = "ERCİŞ" });
            ilceler.Add(new Ilce() { ID = 1236, Sehir_ID = 65, Isim = "ÇATAK" });
            ilceler.Add(new Ilce() { ID = 1175, Sehir_ID = 65, Isim = "BAŞKALE" });
            ilceler.Add(new Ilce() { ID = 1998, Sehir_ID = 66, Isim = "YENİFAKILI" });
            ilceler.Add(new Ilce() { ID = 1982, Sehir_ID = 66, Isim = "SARAYKENT" });
            ilceler.Add(new Ilce() { ID = 1952, Sehir_ID = 66, Isim = "KADIŞEHRİ" });
            ilceler.Add(new Ilce() { ID = 1895, Sehir_ID = 66, Isim = "ÇANDIR" });
            ilceler.Add(new Ilce() { ID = 1877, Sehir_ID = 66, Isim = "AYDINCIK" });
            ilceler.Add(new Ilce() { ID = 1733, Sehir_ID = 66, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1726, Sehir_ID = 66, Isim = "YERKÖY" });
            ilceler.Add(new Ilce() { ID = 1655, Sehir_ID = 66, Isim = "ŞEFAATLİ" });
            ilceler.Add(new Ilce() { ID = 1635, Sehir_ID = 66, Isim = "SORGUN" });
            ilceler.Add(new Ilce() { ID = 1602, Sehir_ID = 66, Isim = "SARIKAYA" });
            ilceler.Add(new Ilce() { ID = 1245, Sehir_ID = 66, Isim = "ÇEKEREK" });
            ilceler.Add(new Ilce() { ID = 1242, Sehir_ID = 66, Isim = "ÇAYIRALAN" });
            ilceler.Add(new Ilce() { ID = 1198, Sehir_ID = 66, Isim = "BOĞAZLIYAN" });
            ilceler.Add(new Ilce() { ID = 1117, Sehir_ID = 66, Isim = "AKDAĞMADENİ" });
            ilceler.Add(new Ilce() { ID = 99147, Sehir_ID = 67, Isim = "Zonguldak Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2101, Sehir_ID = 67, Isim = "KOZLU" });
            ilceler.Add(new Ilce() { ID = 2100, Sehir_ID = 67, Isim = "KİLİMLİ" });
            ilceler.Add(new Ilce() { ID = 1926, Sehir_ID = 67, Isim = "GÖKÇEBEY" });
            ilceler.Add(new Ilce() { ID = 1758, Sehir_ID = 67, Isim = "ALAPLI" });
            ilceler.Add(new Ilce() { ID = 1741, Sehir_ID = 67, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1313, Sehir_ID = 67, Isim = "EREĞLİ" });
            ilceler.Add(new Ilce() { ID = 1276, Sehir_ID = 67, Isim = "DEVREK" });
            ilceler.Add(new Ilce() { ID = 1240, Sehir_ID = 67, Isim = "ÇAYCUMA" });
            ilceler.Add(new Ilce() { ID = 2106, Sehir_ID = 68, Isim = "SULTANHANI" });
            ilceler.Add(new Ilce() { ID = 1932, Sehir_ID = 68, Isim = "GÜLAĞAÇ" });
            ilceler.Add(new Ilce() { ID = 1921, Sehir_ID = 68, Isim = "ESKİL" });
            ilceler.Add(new Ilce() { ID = 1866, Sehir_ID = 68, Isim = "SARIYAHŞİ" });
            ilceler.Add(new Ilce() { ID = 1861, Sehir_ID = 68, Isim = "GÜZELYURT" });
            ilceler.Add(new Ilce() { ID = 1860, Sehir_ID = 68, Isim = "AĞAÇÖREN" });
            ilceler.Add(new Ilce() { ID = 1557, Sehir_ID = 68, Isim = "ORTAKÖY" });
            ilceler.Add(new Ilce() { ID = 1120, Sehir_ID = 68, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1788, Sehir_ID = 69, Isim = "DEMİRÖZÜ" });
            ilceler.Add(new Ilce() { ID = 1767, Sehir_ID = 69, Isim = "AYDINTEPE" });
            ilceler.Add(new Ilce() { ID = 1176, Sehir_ID = 69, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1983, Sehir_ID = 70, Isim = "SARIVELİLER" });
            ilceler.Add(new Ilce() { ID = 1884, Sehir_ID = 70, Isim = "BAŞYAYLA" });
            ilceler.Add(new Ilce() { ID = 1862, Sehir_ID = 70, Isim = "KAZIMKARABEKİR" });
            ilceler.Add(new Ilce() { ID = 1768, Sehir_ID = 70, Isim = "AYRANCI" });
            ilceler.Add(new Ilce() { ID = 1439, Sehir_ID = 70, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1316, Sehir_ID = 70, Isim = "ERMENEK" });
            ilceler.Add(new Ilce() { ID = 1992, Sehir_ID = 71, Isim = "YAHŞİHAN" });
            ilceler.Add(new Ilce() { ID = 1954, Sehir_ID = 71, Isim = "KARAKEÇİLİ" });
            ilceler.Add(new Ilce() { ID = 1901, Sehir_ID = 71, Isim = "ÇELEBİ" });
            ilceler.Add(new Ilce() { ID = 1882, Sehir_ID = 71, Isim = "BALIŞEYH" });
            ilceler.Add(new Ilce() { ID = 1880, Sehir_ID = 71, Isim = "BAHŞİLİ" });
            ilceler.Add(new Ilce() { ID = 1638, Sehir_ID = 71, Isim = "SULAKYURT" });
            ilceler.Add(new Ilce() { ID = 1469, Sehir_ID = 71, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1463, Sehir_ID = 71, Isim = "KESKİN" });
            ilceler.Add(new Ilce() { ID = 1268, Sehir_ID = 71, Isim = "DELİCE" });
            ilceler.Add(new Ilce() { ID = 99108, Sehir_ID = 72, Isim = "Batman Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1941, Sehir_ID = 72, Isim = "HASANKEYF" });
            ilceler.Add(new Ilce() { ID = 1607, Sehir_ID = 72, Isim = "SASON" });
            ilceler.Add(new Ilce() { ID = 1487, Sehir_ID = 72, Isim = "KOZLUK" });
            ilceler.Add(new Ilce() { ID = 1345, Sehir_ID = 72, Isim = "GERCÜŞ" });
            ilceler.Add(new Ilce() { ID = 1184, Sehir_ID = 72, Isim = "BEŞİRİ" });
            ilceler.Add(new Ilce() { ID = 1174, Sehir_ID = 72, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 99118, Sehir_ID = 73, Isim = "Şırnak Şerafettin Elçi Havalimanı" });
            ilceler.Add(new Ilce() { ID = 1931, Sehir_ID = 73, Isim = "GÜÇLÜKONAK" });
            ilceler.Add(new Ilce() { ID = 1698, Sehir_ID = 73, Isim = "ULUDERE" });
            ilceler.Add(new Ilce() { ID = 1661, Sehir_ID = 73, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1623, Sehir_ID = 73, Isim = "SİLOPİ" });
            ilceler.Add(new Ilce() { ID = 1403, Sehir_ID = 73, Isim = "İDİL" });
            ilceler.Add(new Ilce() { ID = 1223, Sehir_ID = 73, Isim = "CİZRE" });
            ilceler.Add(new Ilce() { ID = 1189, Sehir_ID = 73, Isim = "BEYTÜŞŞEBAP" });
            ilceler.Add(new Ilce() { ID = 1761, Sehir_ID = 74, Isim = "AMASRA" });
            ilceler.Add(new Ilce() { ID = 1701, Sehir_ID = 74, Isim = "ULUS" });
            ilceler.Add(new Ilce() { ID = 1496, Sehir_ID = 74, Isim = "KURUCAŞİLE" });
            ilceler.Add(new Ilce() { ID = 1172, Sehir_ID = 74, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 2008, Sehir_ID = 75, Isim = "DAMAL" });
            ilceler.Add(new Ilce() { ID = 1579, Sehir_ID = 75, Isim = "POSOF" });
            ilceler.Add(new Ilce() { ID = 1380, Sehir_ID = 75, Isim = "HANAK" });
            ilceler.Add(new Ilce() { ID = 1356, Sehir_ID = 75, Isim = "GÖLE" });
            ilceler.Add(new Ilce() { ID = 1252, Sehir_ID = 75, Isim = "ÇILDIR" });
            ilceler.Add(new Ilce() { ID = 1144, Sehir_ID = 75, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 99111, Sehir_ID = 76, Isim = "Iğdır Havalimanı" });
            ilceler.Add(new Ilce() { ID = 2011, Sehir_ID = 76, Isim = "KARAKOYUNLU" });
            ilceler.Add(new Ilce() { ID = 1692, Sehir_ID = 76, Isim = "TUZLUCA" });
            ilceler.Add(new Ilce() { ID = 1398, Sehir_ID = 76, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1142, Sehir_ID = 76, Isim = "ARALIK" });
            ilceler.Add(new Ilce() { ID = 2026, Sehir_ID = 77, Isim = "TERMAL" });
            ilceler.Add(new Ilce() { ID = 2022, Sehir_ID = 77, Isim = "ÇİFTLİKKÖY" });
            ilceler.Add(new Ilce() { ID = 2021, Sehir_ID = 77, Isim = "ÇINARCIK" });
            ilceler.Add(new Ilce() { ID = 2020, Sehir_ID = 77, Isim = "ARMUTLU" });
            ilceler.Add(new Ilce() { ID = 2019, Sehir_ID = 77, Isim = "ALTINOVA" });
            ilceler.Add(new Ilce() { ID = 1716, Sehir_ID = 77, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1856, Sehir_ID = 78, Isim = "YENİCE" });
            ilceler.Add(new Ilce() { ID = 1587, Sehir_ID = 78, Isim = "SAFRANBOLU" });
            ilceler.Add(new Ilce() { ID = 1561, Sehir_ID = 78, Isim = "OVACIK" });
            ilceler.Add(new Ilce() { ID = 1433, Sehir_ID = 78, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1321, Sehir_ID = 78, Isim = "ESKİPAZAR" });
            ilceler.Add(new Ilce() { ID = 1296, Sehir_ID = 78, Isim = "EFLANİ" });
            ilceler.Add(new Ilce() { ID = 2025, Sehir_ID = 79, Isim = "POLATELİ" });
            ilceler.Add(new Ilce() { ID = 2024, Sehir_ID = 79, Isim = "MUSABEYLİ" });
            ilceler.Add(new Ilce() { ID = 2023, Sehir_ID = 79, Isim = "ELBEYLİ" });
            ilceler.Add(new Ilce() { ID = 1476, Sehir_ID = 79, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 2029, Sehir_ID = 80, Isim = "TOPRAKKALE" });
            ilceler.Add(new Ilce() { ID = 2028, Sehir_ID = 80, Isim = "SUMBAS" });
            ilceler.Add(new Ilce() { ID = 2027, Sehir_ID = 80, Isim = "HASANBEYLİ" });
            ilceler.Add(new Ilce() { ID = 1743, Sehir_ID = 80, Isim = "DÜZİÇİ" });
            ilceler.Add(new Ilce() { ID = 1560, Sehir_ID = 80, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1423, Sehir_ID = 80, Isim = "KADİRLİ" });
            ilceler.Add(new Ilce() { ID = 1165, Sehir_ID = 80, Isim = "BAHÇE" });
            ilceler.Add(new Ilce() { ID = 2031, Sehir_ID = 81, Isim = "KAYNAŞLI" });
            ilceler.Add(new Ilce() { ID = 2017, Sehir_ID = 81, Isim = "GÜMÜŞOVA" });
            ilceler.Add(new Ilce() { ID = 1905, Sehir_ID = 81, Isim = "ÇİLİMLİ" });
            ilceler.Add(new Ilce() { ID = 1794, Sehir_ID = 81, Isim = "GÖLYAKA" });
            ilceler.Add(new Ilce() { ID = 1784, Sehir_ID = 81, Isim = "CUMAYERİ" });
            ilceler.Add(new Ilce() { ID = 1730, Sehir_ID = 81, Isim = "YIĞILCA" });
            ilceler.Add(new Ilce() { ID = 1292, Sehir_ID = 81, Isim = "MERKEZ" });
            ilceler.Add(new Ilce() { ID = 1116, Sehir_ID = 81, Isim = "AKÇAKOCA" });

        }

        private void cb_sehirler_SelectedIndexChanged(object sender, EventArgs e)
        {
            Sehir secilen = (Sehir)cb_sehirler.SelectedItem;
            int sehirID = secilen.ID;

            List<Ilce> secilenIlceler = new List<Ilce>();

            for (int i = 0; i < ilceler.Count; i++)
            {
                if (ilceler[i].Sehir_ID == sehirID)
                {
                    secilenIlceler.Add(ilceler[i]);
                }
            }

            cb_ilceler.DataSource = secilenIlceler;

        }
    }
}
